version: '3.8'

services:
  # PostgreSQL Database
  fairdoc-postgres:
    image: postgres:13
    container_name: fairdoc-postgres
    environment:
      POSTGRES_DB: fairdoc_v0
      POSTGRES_USER: fairdoc
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis Cache
  fairdoc-redis:
    image: redis:7-alpine
    container_name: fairdoc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # MinIO Object Storage
  fairdoc-minio:
    image: minio/minio
    container_name: fairdoc-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data:
