"""
NICE Lookup Service for Fairdoc AI
Provides lightweight symptom-to-protocol retrieval under 120 LOC.
"""
from __future__ import annotations

import re
from functools import cached_property
from typing import Dict, List, Optional

import structlog

# Seed data is defined in the database layer to avoid duplication.
from src.app2.models.database.nice_protocols import NICE_SEED_DATA

logger = structlog.get_logger(__name__)


class NICELookupService:  # pylint: disable=too-few-public-methods
    """Map free-text symptoms to a NICE guideline snippet.

    The service relies on *exact* keyword matches against the
    ``primary_symptoms`` field inside each protocol.  This keeps
    complexity low while allowing future extension to fuzzy search or
    vector retrieval without touching the public interface.
    """

    def __init__(self, seed_data: Optional[List[Dict]] = None) -> None:
        self._protocols = seed_data or NICE_SEED_DATA

    # ---------------------------------------------------------------------
    # Internal helpers
    # ---------------------------------------------------------------------
    @cached_property
    def _index(self) -> Dict[str, Dict]:
        """Lower-case keyword → protocol mapping built once per instance."""
        index: Dict[str, Dict] = {}
        for proto in self._protocols:
            for symptom in proto["primary_symptoms"]:
                index[symptom.lower()] = proto
        logger.debug("NICE index built", size=len(index))
        return index

    @staticmethod
    def _clean_text(text: str) -> List[str]:
        """Tokenise *very* roughly—good enough for keyword lookup."""
        return re.findall(r"[a-zA-Z_]+", text.lower())

    @staticmethod
    def _format_protocol(proto: Dict) -> str:
        """Flatten the protocol dict into a readable multi-line string."""
        questions = proto["initial_questions"] + proto["follow_up_questions"]
        return (
            f"Condition: {proto['condition_name']}\n"
            f"Emergency criteria: {proto['emergency_criteria']}\n"
            f"Routine criteria: {proto['routine_criteria']}\n"
            f"Self-care criteria: {proto['self_care_criteria']}\n"
            "Questions:\n  • " + "\n  • ".join(questions)
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def find_relevant_protocols(self, symptom_text: str) -> Dict[str, str]:
        """Enhanced protocol matching with medical synonyms"""
        tokens = self._clean_text(symptom_text)
        
        # Add medical synonym expansion
        expanded_tokens = tokens.copy()
        medical_synonyms = {
            'pain': ['ache', 'hurt', 'discomfort', 'sore', 'aching', 'agony', 'suffering', 'torment', 'throbbing', 'stabbing', 'burning', 'cramping', 'sharp', 'dull', 'chronic pain', 'acute pain'],
            'breath': ['breathing', 'breathe', 'dyspnea', 'shortness', 'respiration', 'inhalation', 'exhalation', 'wheezing', 'gasping', 'panting', 'hyperventilation', 'hypoventilation'],
            'chest': ['thoracic', 'cardiac', 'heart', 'breast', 'sternum', 'ribcage', 'pectoral', 'thorax', 'breastbone', 'intercostal'],
            'head': ['headache', 'cephalgia', 'skull', 'cranium', 'brain', 'migraine', 'tension headache', 'cluster headache', 'cephalic', 'cranial'],
            'stomach': ['abdominal', 'belly', 'gastric', 'gut', 'abdomen', 'tummy', 'epigastric', 'gastro', 'ventral', 'peritoneal'],
            'heart': ['cardiac', 'myocardial', 'coronary', 'cardiovascular', 'cardio', 'myocardium', 'pericardial', 'atrial', 'ventricular', 'aortic'],
            'lung': ['pulmonary', 'respiratory', 'pneumo-', 'bronchial', 'alveolar', 'pleural', 'thoracic', 'pneumonic', 'broncho'],
            'kidney': ['renal', 'nephro-', 'nephritic', 'urinary', 'glomerular', 'tubular', 'cortical', 'medullary'],
            'liver': ['hepatic', 'hepat-', 'hepatocellular', 'biliary', 'cholangial', 'portal', 'lobular'],
            'brain': ['cerebral', 'neurological', 'encephalon', 'cranium', 'cortical', 'subcortical', 'neural', 'CNS', 'cerebellum', 'brainstem'],
            'bone': ['osseous', 'skeletal', 'osteo', 'cortical bone', 'trabecular', 'cancellous', 'compact bone', 'periosteal'],
            'skin': ['dermal', 'cutaneous', 'epidermal', 'subcutaneous', 'integumentary', 'dermatologic', 'superficial', 'hypodermic'],
            'joint': ['articular', 'synovial', 'articulation', 'arthro', 'capsular', 'ligamentous', 'cartilaginous'],
            'muscle': ['muscular', 'myo-', 'sarc-', 'myofascial', 'skeletal muscle', 'smooth muscle', 'striated', 'contractile'],
            'blood': ['hematologic', 'vascular', 'sanguineous', 'hemato', 'circulatory', 'plasma', 'serum', 'hemic'],
            'fever': ['pyrexia', 'hyperthermia', 'febrile', 'temperature', 'elevated temperature', 'feverishness', 'pyretic'],
            'cough': ['tussis', 'hacking', 'expectoration', 'sputum', 'productive cough', 'dry cough', 'barking cough', 'whooping'],
            'dizziness': ['vertigo', 'lightheadedness', 'unsteadiness', 'giddiness', 'wooziness', 'disequilibrium', 'spinning'],
            'nausea': ['queasy', 'sick to stomach', 'emetic', 'queasiness', 'stomach upset', 'motion sickness', 'morning sickness'],
            'vomiting': ['emesis', 'throwing up', 'regurgitation', 'puking', 'retching', 'heaving', 'upchucking', 'expulsion'],
            'fatigue': ['tiredness', 'lethargy', 'malaise', 'exhaustion', 'weakness', 'weariness', 'lassitude', 'asthenia'],
            'swelling': ['edema', 'inflammation', 'tumefaction', 'engorgement', 'distension', 'puffiness', 'bloating', 'enlargement'],
            'rash': ['exanthem', 'dermatitis', 'eruption', 'skin lesion', 'breakout', 'hives', 'urticaria', 'eczema'],
            'diarrhea': ['loose stools', 'bowel movements', 'watery stools', 'loose bowels', 'runny stool', 'liquid stool'],
            'constipation': ['hard stools', 'difficulty with bowel movements', 'obstipation', 'irregular bowel movements', 'blocked bowels'],
            'hypertension': ['high blood pressure', 'HTN', 'elevated BP', 'arterial hypertension', 'systolic hypertension'],
            'diabetes': ['mellitus', 'DM', 'high blood sugar', 'hyperglycemia', 'insulin resistance', 'glucose intolerance'],
            'cancer': ['malignancy', 'neoplasm', 'carcinoma', 'tumor', 'oncological', 'malignant tumor', 'sarcoma', 'adenocarcinoma'],
            'asthma': ['reactive airway disease', 'wheezing', 'bronchospasm', 'allergic asthma', 'exercise-induced asthma'],
            'arthritis': ['joint inflammation', 'osteoarthritis', 'rheumatoid arthritis', 'degenerative joint disease', 'inflammatory arthritis'],
            'hepatitis': ['liver inflammation', 'viral hepatitis', 'chronic hepatitis', 'acute hepatitis', 'hepatic inflammation'],
            'fracture': ['broken bone', 'break', 'bone break', 'hairline fracture', 'compound fracture', 'simple fracture'],
            'stroke': ['cerebrovascular accident', 'CVA', 'brain attack', 'ischemic stroke', 'hemorrhagic stroke', 'TIA'],
            'heart attack': ['myocardial infarction', 'MI', 'coronary thrombosis', 'cardiac arrest', 'coronary occlusion'],
            'anemia': ['low red blood cell count', 'low hemoglobin', 'iron deficiency', 'blood deficiency', 'low hematocrit'],
            'biopsy': ['tissue sample', 'pathology test', 'needle biopsy', 'surgical biopsy', 'fine needle aspiration'],
            'surgery': ['operation', 'procedure', 'surgical intervention', 'operative procedure', 'surgical treatment'],
            'x-ray': ['radiograph', 'imaging', 'roentgenogram', 'plain film', 'diagnostic imaging'],
            'mri': ['magnetic resonance imaging', 'nuclear magnetic resonance', 'MR imaging', 'magnetic resonance'],
            'ecg': ['electrocardiogram', 'ekg', 'cardiac monitoring', 'heart rhythm strip', 'ECG tracing'],
            'blood test': ['lab work', 'venipuncture', 'blood draw', 'phlebotomy', 'laboratory test'],
            'acute': ['sudden onset', 'severe', 'short duration', 'rapid', 'immediate', 'abrupt', 'quick'],
            'chronic': ['long-term', 'persistent', 'long duration', 'ongoing', 'prolonged', 'enduring', 'continuous'],
            'benign': ['non-cancerous', 'harmless', 'not malignant', 'non-threatening', 'innocent', 'mild'],
            'malignant': ['cancerous', 'harmful', 'invasive', 'aggressive', 'metastatic', 'dangerous'],
            'etiology': ['cause', 'origin', 'source', 'root cause', 'causation', 'pathogenesis'],
            'prognosis': ['outlook', 'likely outcome', 'forecast', 'prediction', 'expectation', 'prospect'],
            'treatment': ['therapy', 'management', 'interventions', 'care', 'remedy', 'therapeutic approach'],
            'diagnosis': ['identification', 'assessment', 'evaluation', 'determination', 'clinical diagnosis'],
            'hives': ['urticaria', 'wheals', 'welts', 'skin bumps', 'allergic reaction', 'raised rash'],
            'gastroenteritis': ['stomach flu', 'stomach bug', 'intestinal flu', 'viral gastroenteritis', 'food poisoning'],
            'influenza': ['flu', 'grippe', 'viral infection', 'seasonal flu', 'respiratory flu'],
            'pharyngitis': ['sore throat', 'strep throat', 'throat infection', 'throat inflammation', 'tonsillitis'],
            'edema': ['swelling', 'fluid retention', 'water retention', 'tissue swelling', 'lymphedema'],
            'pneumonia': ['lung infection', 'pneumonitis', 'pulmonary infection', 'chest infection', 'bronchopneumonia'],
            'hypotension': ['low blood pressure', 'decreased BP', 'arterial hypotension', 'orthostatic hypotension'],
            'tachycardia': ['rapid heart rate', 'fast heart rate', 'increased heart rate', 'accelerated pulse'],
            'bradycardia': ['slow heart rate', 'decreased heart rate', 'reduced pulse', 'low heart rate'],
            'dyspnea': ['shortness of breath', 'breathlessness', 'difficulty breathing', 'labored breathing'],
            'apnea': ['cessation of breathing', 'stopped breathing', 'breath holding', 'respiratory arrest'],
            'jaundice': ['icterus', 'yellowing of the skin', 'yellowing', 'yellow discoloration', 'bilirubin excess'],
            'cyanosis': ['blue discoloration', 'bluish color', 'blue tinge', 'oxygen deficiency', 'hypoxic discoloration'],
            'erythema': ['redness', 'flushing', 'red discoloration', 'inflammatory redness', 'hyperemia'],
            'pruritus': ['itching', 'itch', 'skin irritation', 'scratching', 'itchy sensation'],
            'hemorrhage': ['bleeding', 'blood loss', 'hemorrhaging', 'internal bleeding', 'external bleeding'],
            'hematoma': ['bruise', 'blood clot', 'ecchymosis', 'contusion', 'blood collection'],
            'laceration': ['cut', 'gash', 'tear', 'wound', 'open wound'],
            'contusion': ['bruise', 'bruising', 'soft tissue injury', 'blunt trauma'],
            'abrasion': ['scrape', 'graze', 'skin abrasion', 'surface wound', 'road rash'],
            'seizure': ['convulsion', 'fit', 'epileptic episode', 'grand mal', 'petit mal'],
            'syncope': ['fainting', 'passing out', 'loss of consciousness', 'blackout', 'collapse'],
            'vertigo': ['dizziness', 'spinning sensation', 'balance disorder', 'inner ear problem'],
            'ambulatory': ['walking', 'able to walk', 'mobile', 'outpatient', 'non-bedridden'],
            'sedentary': ['inactive', 'sitting', 'immobile', 'bedridden', 'non-ambulatory'],
            'parenteral': ['by injection', 'intravenous', 'not oral', 'IV administration'],
            'oral': ['by mouth', 'PO', 'per os', 'swallowed', 'ingested'],
            'topical': ['on the skin', 'external application', 'dermal application', 'surface application'],
            'subcutaneous': ['under the skin', 'subQ', 'hypodermic', 'beneath skin surface'],
            'intramuscular': ['into the muscle', 'IM', 'muscle injection', 'deep injection'],
            'intravenous': ['into the vein', 'IV', 'venous access', 'direct to bloodstream'],
            'dermatology': ['skin medicine', 'skin specialty', 'dermatologic care', 'skin disorders'],
            'cardiology': ['heart medicine', 'cardiac specialty', 'cardiovascular medicine', 'heart care'],
            'neurology': ['nerve medicine', 'neurological specialty', 'brain medicine', 'nervous system'],
            'orthopedics': ['bone and joint medicine', 'musculoskeletal medicine', 'orthopedic surgery'],
            'gastroenterology': ['stomach and intestine medicine', 'GI medicine', 'digestive system'],
            'pediatrics': ["children's medicine", 'pediatric', 'child healthcare', 'infant care'],
            'geriatrics': ['elderly medicine', 'geriatric', 'senior care', 'aging medicine'],
            'oncology': ['cancer medicine', 'cancer care', 'tumor treatment', 'malignancy treatment'],
            'pathology': ['disease study', 'tissue analysis', 'diagnostic pathology', 'laboratory medicine'],
            'radiology': ['imaging study', 'medical imaging', 'diagnostic radiology', 'radiologic diagnosis'],
            'hematology': ['blood study', 'blood disorders', 'hematologic medicine', 'blood diseases'],
            'nephrology': ['kidney study', 'renal medicine', 'kidney diseases', 'urinary system'],
            'pulmonology': ['lung study', 'respiratory medicine', 'chest medicine', 'breathing disorders'],
            'endocrinology': ['hormone study', 'endocrine medicine', 'glandular disorders', 'metabolic medicine'],
            'urology': ['urinary system study', 'genitourinary medicine', 'kidney and bladder'],
            'gynecology': ['female reproductive system study', 'women\'s health', 'gynecologic care'],
            'obstetrics': ['pregnancy and childbirth', 'maternity', 'prenatal care', 'delivery medicine'],
            'otolaryngology': ['ear, nose, and throat medicine', 'ent', 'head and neck surgery'],
            'ophthalmology': ['eye medicine', 'vision care', 'ocular medicine', 'eye disorders'],
            'psychiatry': ['mental health medicine', 'psychological medicine', 'behavioral health'],
            'immunology': ['immune system study', 'allergy medicine', 'immunologic disorders'],
            'rheumatology': ['autoimmune and joint disease study', 'connective tissue disorders'],
            'remission': ['disease free', 'symptom free', 'regression', 'temporary recovery'],
            'recurrence': ['return of disease', 'relapse', 'comeback', 'reappearance'],
            'metastasis': ['spread of cancer', 'metastasize', 'cancer spreading', 'distant spread'],
            'palliative': ['comfort care', 'symptom management', 'supportive care', 'pain relief'],
            'curative': ['intended to cure', 'healing treatment', 'restorative therapy'],
            'idiopathic': ['unknown cause', 'spontaneous', 'primary', 'of unknown origin'],
            'iatrogenic': ['caused by medical treatment', 'treatment-induced', 'physician-caused'],
            'nosocomial': ['hospital-acquired', 'healthcare-associated', 'institutional infection'],
            'hereditary': ['genetic', 'inherited', 'familial', 'congenital', 'passed down'],
            'congenital': ['present at birth', 'inborn', 'natal', 'developmental'],
            'subacute': ['in between acute and chronic', 'moderately severe', 'intermediate'],
            'asymptomatic': ['without symptoms', 'silent', 'subclinical', 'symptom-free'],
            'symptomatic': ['with symptoms', 'clinical', 'manifest', 'apparent'],
            'epidemiology': ['study of disease patterns in populations', 'public health study'],
            'pharmacology': ['study of drugs', 'medication science', 'drug therapy'],
            'toxicology': ['study of poisons', 'poison science', 'toxic substances'],
            'teratology': ['study of birth defects', 'developmental abnormalities'],
            'gerontology': ['study of aging', 'geriatric medicine', 'elderly care'],
            'anorexia': ['loss of appetite', 'decreased eating', 'appetite suppression'],
            'cachexia': ['wasting syndrome', 'muscle wasting', 'severe weight loss'],
            'dysphagia': ['difficulty swallowing', 'swallowing disorder', 'deglutition problem'],
            'dysarthria': ['difficulty speaking', 'speech disorder', 'articulation problem'],
            'aphasia': ['loss of speech', 'language disorder', 'communication impairment'],
            'amnesia': ['memory loss', 'forgetfulness', 'memory impairment'],
            'insomnia': ['inability to sleep', 'sleeplessness', 'sleep disorder'],
            'narcolepsy': ['uncontrollable sleep attacks', 'excessive daytime sleepiness'],
            'tinnitus': ['ringing in the ears', 'ear noise', 'auditory phantom'],
            'otitis': ['ear inflammation', 'ear infection', 'auricular inflammation'],
            'rhinitis': ['nose inflammation', 'nasal inflammation', 'runny nose'],
            'sinusitis': ['sinus inflammation', 'sinus infection', 'blocked sinuses'],
            'conjunctivitis': ['pink eye', 'eye inflammation', 'red eyes'],
            'cataract': ['cloudy lens', 'lens opacity', 'vision impairment'],
            'glaucoma': ['increased eye pressure', 'optic nerve damage', 'vision loss'],
            'myopia': ['nearsightedness', 'short sight', 'close vision'],
            'hyperopia': ['farsightedness', 'long sight', 'distant vision'],
            'presbyopia': ['age-related farsightedness', 'reading difficulty'],
            'astigmatism': ['blurred vision', 'distorted vision', 'irregular cornea'],
            'dementia': ['cognitive decline', 'mental deterioration', 'memory loss'],
            'alzheimer\'s': ['ad', 'progressive memory loss', 'senile dementia'],
            'parkinson\'s': ['pd', 'shaking palsy', 'movement disorder'],
            'epilepsy': ['seizure disorder', 'convulsive disorder', 'brain electrical disorder'],
            'multiple sclerosis': ['ms', 'demyelinating disease', 'autoimmune neurologic'],
            'lupus': ['sle', 'systemic lupus erythematosus', 'autoimmune disease'],
            'psoriasis': ['scaly skin condition', 'chronic skin disease', 'plaque psoriasis'],
            'eczema': ['atopic dermatitis', 'skin inflammation', 'allergic skin reaction'],
            'cellulitis': ['skin infection', 'soft tissue infection', 'bacterial skin infection'],
            'abscess': ['pus pocket', 'infected collection', 'localized infection'],
            'ulcer': ['open sore', 'lesion', 'wound', 'erosion'],
            'decubitus ulcer': ['pressure sore', 'bed sore', 'pressure ulcer'],
            'gangrene': ['tissue death', 'necrotic tissue', 'dead tissue'],
            'necrosis': ['tissue death', 'cell death', 'dead cells'],
            'ischemia': ['reduced blood flow', 'decreased circulation', 'oxygen deficiency'],
            'infarction': ['tissue death from ischemia', 'dead tissue from blocked blood'],
            'arrhythmia': ['irregular heart rhythm', 'abnormal heartbeat', 'rhythm disorder'],
            'fibrillation': ['quivering heart', 'chaotic heart rhythm', 'irregular contractions'],
            'atherosclerosis': ['hardening of the arteries', 'arterial plaque', 'vascular disease'],
            'embolism': ['blood clot blocking an artery', 'traveling clot', 'vascular obstruction'],
            'thrombosis': ['blood clot formation', 'clot development', 'coagulation'],
            'aneurysm': ['bulging artery', 'arterial dilation', 'vessel ballooning'],
            'angina': ['chest pain', 'cardiac pain', 'heart pain'],
            'congestive heart failure': ['chf', 'heart failure', 'cardiac insufficiency'],
            'copd': ['chronic obstructive pulmonary disease', 'lung disease', 'breathing disorder'],
            'bronchitis': ['airway inflammation', 'bronchial inflammation', 'chest cold'],
            'emphysema': ['lung damage', 'alveolar destruction', 'breathing difficulty'],
            'tuberculosis': ['tb', 'consumption', 'pulmonary tuberculosis'],
            'cystitis': ['bladder infection', 'urinary tract infection', 'bladder inflammation'],
            'pyelonephritis': ['kidney infection', 'renal infection', 'upper UTI'],
            'nephritis': ['kidney inflammation', 'renal inflammation', 'glomerulonephritis'],
            'renal failure': ['kidney failure', 'kidney dysfunction', 'renal insufficiency'],
            'dialysis': ['kidney treatment', 'artificial kidney', 'blood cleaning'],
            'cirrhosis': ['liver scarring', 'hepatic fibrosis', 'liver damage'],
            'cholecystitis': ['gallbladder inflammation', 'gallbladder infection'],
            'pancreatitis': ['pancreas inflammation', 'pancreatic inflammation'],
            'gastritis': ['stomach inflammation', 'gastric inflammation', 'stomach irritation'],
            'appendicitis': ['appendix inflammation', 'appendiceal inflammation'],
            'colitis': ['colon inflammation', 'large bowel inflammation'],
            'diverticulitis': ['colon pouch inflammation', 'diverticular disease'],
            'hernia': ['protrusion of an organ', 'organ displacement', 'tissue protrusion'],
            'inguinal hernia': ['groin hernia', 'groin protrusion'],
            'hiatal hernia': ['stomach hernia', 'esophageal hernia'],
            'hemorrhoids': ['piles', 'rectal veins', 'anal cushions'],
            'gastroesophageal reflux disease': ['gerd', 'heartburn', 'acid reflux'],
            'irritable bowel syndrome': ['ibs', 'spastic colon', 'functional bowel disorder'],
            'crohn\'s disease': ['inflammatory bowel disease', 'ibd', 'regional enteritis'],
            'ulcerative colitis': ['inflammatory bowel disease', 'ibd', 'chronic colitis'],
            'hypothyroidism': ['underactive thyroid', 'low thyroid', 'thyroid deficiency'],
            'hyperthyroidism': ['overactive thyroid', 'high thyroid', 'thyroid excess'],
            'graves\' disease': ['hyperthyroidism', 'thyroid autoimmune disease'],
            'hashimoto\'s thyroiditis': ['hypothyroidism', 'autoimmune thyroiditis'],
            'adrenal insufficiency': ['addison\'s disease', 'adrenal failure'],
            'cushing\'s syndrome': ['high cortisol', 'hypercortisolism'],
            'acromegaly': ['gigantism', 'growth hormone excess', 'enlarged features'],
            'menopause': ['climacteric', 'change of life', 'cessation of menses'],
            'pregnancy': ['gestation', 'gravidity', 'expecting', 'with child'],
            'labor': ['childbirth', 'parturition', 'delivery', 'birth process'],
            'ectopic pregnancy': ['tubal pregnancy', 'extrauterine pregnancy'],
            'endometriosis': ['uterine tissue outside uterus', 'endometrial implants'],
            'fibroids': ['leiomyoma', 'uterine tumors', 'myomas'],
            'prostate enlargement': ['bph', 'benign prostatic hyperplasia', 'enlarged prostate'],
            'prostatitis': ['prostate inflammation', 'prostate infection'],
            'epididymitis': ['epididymis inflammation', 'testicular appendage infection'],
            'orchitis': ['testicle inflammation', 'testicular inflammation'],
            'sexually transmitted infection': ['sti', 'std', 'venereal disease'],
            'hiv': ['human immunodeficiency virus', 'aids', 'acquired immunodeficiency'],
            'herpes': ['hsv', 'herpes simplex', 'cold sores'],
            'syphilis': ['lues', 'great pox', 'treponema infection'],
            'gonorrhea': ['the clap', 'gonococcal infection'],
            'chlamydia': ['ct', 'chlamydial infection'],
            'hpv': ['human papillomavirus', 'genital warts'],
            'meningitis': ['brain membrane inflammation', 'meningeal infection'],
            'encephalitis': ['brain inflammation', 'cerebral inflammation'],
            'myelitis': ['spinal cord inflammation', 'spinal inflammation'],
            'neuropathy': ['nerve damage', 'peripheral neuropathy', 'nerve disorder'],
            'neuralgia': ['nerve pain', 'neuralgic pain'],
            'sciatica': ['sciatic nerve pain', 'radicular pain'],
            'carpal tunnel syndrome': ['cts', 'median nerve compression'],
            'tendonitis': ['tendon inflammation', 'tendinitis'],
            'bursitis': ['bursa inflammation', 'joint sac inflammation'],
            'osteoporosis': ['bone thinning', 'bone density loss', 'brittle bones'],
            'osteomyelitis': ['bone infection', 'bone inflammation'],
            'lumbago': ['low back pain', 'lumbar pain'],
            'scoliosis': ['spinal curvature', 'curved spine'],
            'kyphosis': ['hunchback', 'forward spine curve'],
            'lordosis': ['swayback', 'inward spine curve'],
            'sprain': ['ligament injury', 'stretched ligament'],
            'strain': ['muscle or tendon injury', 'pulled muscle'],
            'dislocation': ['joint separation', 'displaced joint'],
            'amputation': ['removal of a limb', 'surgical removal'],
            'prosthesis': ['artificial limb', 'replacement device'],
            'orthosis': ['brace', 'support device'],
            'splint': ['immobilizer', 'stabilizing device'],
            'cast': ['plaster cast', 'immobilization device'],
            'analgesic': ['painkiller', 'pain reliever', 'pain medication'],
            'antibiotic': ['germ killer', 'antibacterial', 'antimicrobial'],
            'antipyretic': ['fever reducer', 'fever medication'],
            'antihistamine': ['allergy medicine', 'histamine blocker'],
            'anti-inflammatory': ['inflammation reducer', 'anti-inflammatory drug'],
            'anticoagulant': ['blood thinner', 'clotting preventer'],
            'antidepressant': ['mood elevator', 'depression medication'],
            'antipsychotic': ['psychosis medicine', 'antipsychotic drug'],
            'anesthetic': ['numbing agent', 'pain blocker'],
            'sedative': ['calming agent', 'tranquilizer'],
            'diuretic': ['water pill', 'fluid reducer'],
            'vasodilator': ['blood vessel opener', 'vessel relaxer'],
            'bronchodilator': ['airway opener', 'breathing medication'],
            'insulin': ['diabetes hormone', 'blood sugar medication'],
            'chemotherapy': ['chemo', 'cancer drug treatment', 'cytotoxic therapy'],
            'radiotherapy': ['radiation therapy', 'radiation treatment'],
            'immunotherapy': ['immune system treatment', 'biological therapy'],
            'autopsy': ['postmortem examination', 'post-mortem', 'necropsy'],
            'endoscopy': ['scope procedure', 'internal examination'],
            'colonoscopy': ['colon scope', 'large bowel examination'],
            'gastroscopy': ['stomach scope', 'upper endoscopy'],
            'laparoscopy': ['keyhole surgery', 'minimally invasive surgery'],
            'arthroscopy': ['joint scope', 'joint examination'],
            'angiography': ['blood vessel imaging', 'vascular imaging'],
            'ultrasound': ['sonogram', 'ultrasonic imaging'],
            'ct scan': ['computed tomography', 'cat scan'],
            'eeg': ['electroencephalogram', 'brain wave test'],
            'emg': ['electromyogram', 'muscle electrical test'],
            'bp': ['blood pressure', 'arterial pressure'],
            'hr': ['heart rate', 'pulse rate'],
            'rr': ['respiratory rate', 'breathing rate'],
            't': ['temperature', 'body temperature'],
            'o2 sat': ['oxygen saturation', 'blood oxygen level'],
            'wbc': ['white blood cell count', 'leukocyte count'],
            'rbc': ['red blood cell count', 'erythrocyte count'],
            'hgb': ['hemoglobin', 'blood protein'],
            'hct': ['hematocrit', 'packed cell volume'],
            'plt': ['platelets', 'thrombocytes'],
            'na': ['sodium', 'serum sodium'],
            'k': ['potassium', 'serum potassium'],
            'cl': ['chloride', 'serum chloride'],
            'co2': ['carbon dioxide', 'bicarbonate'],
            'bun': ['blood urea nitrogen', 'urea nitrogen'],
            'cr': ['creatinine', 'serum creatinine'],
            'glu': ['glucose', 'blood sugar'],
            'ca': ['calcium', 'serum calcium'],
            'mg': ['magnesium', 'serum magnesium'],
            'p': ['phosphorus', 'serum phosphate'],
            'lfts': ['liver function tests', 'hepatic panel'],
            'bmp': ['basic metabolic panel', 'chemistry 8'],
            'cmp': ['comprehensive metabolic panel', 'chemistry 14'],
            'cbc': ['complete blood count', 'full blood count'],
            'ua': ['urinalysis', 'urine test'],
            'csf': ['cerebrospinal fluid', 'spinal fluid'],
            'cxr': ['chest x-ray', 'chest radiograph'],
            'kub': ['kidneys, ureters, bladder x-ray', 'abdominal x-ray'],
            'anxiety': ['worry', 'stress', 'fear', 'nervousness', 'apprehension', 'panic'],
            'depression': ['sadness', 'despair', 'low mood', 'melancholy', 'dejection'],
            'inflammation': ['swelling', 'redness', 'heat', 'pain', 'irritation'],
            'infection': ['contamination', 'sepsis', 'bacterial invasion', 'viral invasion'],
            'dehydration': ['fluid loss', 'water deficit', 'volume depletion'],
            'obesity': ['overweight', 'excessive weight', 'adiposity', 'corpulence'],
            'malnutrition': ['undernutrition', 'nutrient deficiency', 'poor nutrition'],
            'allergy': ['hypersensitivity', 'allergic reaction', 'immune response'],
            'trauma': ['injury', 'wound', 'damage', 'harm'],
            'shock': ['circulatory collapse', 'cardiovascular collapse', 'hypoperfusion'],
            'coma': ['unconsciousness', 'deep unconsciousness', 'unresponsive state'],
            'paralysis': ['loss of movement', 'immobility', 'motor dysfunction', 'plegia'],
            'spasm': ['muscle contraction', 'cramp', 'involuntary contraction', 'tetany'],
            'tremor': ['shaking', 'trembling', 'quivering', 'vibration'],
            'rigidity': ['stiffness', 'inflexibility', 'muscle tension', 'spasticity'],
            'weakness': ['asthenia', 'debility', 'feebleness', 'lack of strength'],
            'numbness': ['loss of sensation', 'tingling', 'paresthesia', 'pins and needles'],
            'blindness': ['vision loss', 'sightlessness', 'visual impairment', 'amaurosis'],
            'deafness': ['hearing loss', 'auditory impairment', 'hearing deficit'],
            'muteness': ['inability to speak', 'speechlessness', 'vocal impairment'],
            'incontinence': ['loss of control', 'involuntary release', 'bladder dysfunction'],
            'retention': ['inability to void', 'urinary retention', 'blocked flow'],
            'obstruction': ['blockage', 'occlusion', 'barrier', 'impediment'],
            'perforation': ['hole', 'rupture', 'tear', 'puncture'],
            'stenosis': ['narrowing', 'constriction', 'stricture', 'tightening'],
            'dilation': ['widening', 'expansion', 'enlargement', 'distension'],
            'prolapse': ['organ displacement', 'falling down', 'herniation', 'protrusion'],
            'adhesion': ['scar tissue', 'fibrous band', 'tissue attachment'],
            'calcification': ['calcium deposits', 'hardening', 'mineralization'],
            'fibrosis': ['scarring', 'fibrous tissue', 'tissue thickening'],
            'atrophy': ['wasting', 'shrinkage', 'tissue loss', 'degeneration'],
            'hypertrophy': ['enlargement', 'overgrowth', 'tissue expansion'],
            'hyperplasia': ['cell multiplication', 'tissue overgrowth', 'cell proliferation'],
            'dysplasia': ['abnormal development', 'cellular abnormality', 'tissue irregularity'],
            'metaplasia': ['cell transformation', 'tissue change', 'cellular adaptation'],
            'anaplasia': ['cellular dedifferentiation', 'loss of structure', 'primitive cells'],
            'neoplasia': ['new growth', 'tumor formation', 'abnormal proliferation'],
            'malformation': ['birth defect', 'developmental abnormality', 'structural defect'],
            'deformity': ['abnormal shape', 'distortion', 'structural abnormality'],
            'asymmetry': ['unevenness', 'imbalance', 'lack of symmetry'],
            'lesion': ['abnormality', 'damage', 'pathological change', 'tissue alteration'],
            'nodule': ['small lump', 'growth', 'mass', 'bump'],
            'polyp': ['growth', 'protrusion', 'benign tumor', 'tissue projection'],
            'cyst': ['fluid-filled sac', 'cavity', 'closed sac', 'fluid collection'],
            'granuloma': ['inflammatory mass', 'tissue reaction', 'chronic inflammation'],
            'thrombus': ['blood clot', 'coagulum', 'clotted blood'],
            'embolus': ['traveling clot', 'detached clot', 'circulating obstruction'],
            'plaque': ['fatty deposit', 'arterial buildup', 'atherosclerotic deposit'],
            'exudate': ['inflammatory fluid', 'discharge', 'secretion', 'effusion'],
            'transudate': ['filtered fluid', 'clear fluid', 'non-inflammatory fluid'],
            'effusion': ['fluid collection', 'accumulated fluid', 'fluid buildup'],
            'ascites': ['abdominal fluid', 'peritoneal fluid', 'belly fluid'],
            'hydrocephalus': ['water on brain', 'brain fluid buildup', 'enlarged ventricles'],
            'pneumothorax': ['collapsed lung', 'air in chest', 'lung deflation'],
            'hemothorax': ['blood in chest', 'pleural bleeding', 'chest blood'],
            'pericardial effusion': ['fluid around heart', 'heart sac fluid'],
            'pleural effusion': ['fluid in chest', 'lung fluid', 'pleural fluid'],
            'joint effusion': ['joint fluid', 'synovial fluid buildup', 'water on knee'],
            'epistaxis': ['nosebleed', 'nasal bleeding', 'rhinorrhagia'],
            'hemoptysis': ['coughing blood', 'bloody sputum', 'lung bleeding'],
            'hematemesis': ['vomiting blood', 'bloody vomit', 'stomach bleeding'],
            'melena': ['black stool', 'tarry stool', 'digested blood'],
            'hematochezia': ['bloody stool', 'rectal bleeding', 'fresh blood'],
            'hematuria': ['blood in urine', 'bloody urine', 'urinary bleeding'],
            'menorrhagia': ['heavy periods', 'excessive bleeding', 'heavy menstruation'],
            'metrorrhagia': ['irregular bleeding', 'breakthrough bleeding', 'abnormal bleeding'],
            'dysmenorrhea': ['painful periods', 'menstrual cramps', 'period pain'],
            'amenorrhea': ['absent periods', 'no menstruation', 'missed periods'],
            'oligomenorrhea': ['infrequent periods', 'irregular periods', 'scanty menstruation'],
            'dyspareunia': ['painful intercourse', 'painful sex', 'coital pain'],
            'impotence': ['erectile dysfunction', 'inability to maintain erection'],
            'sterility': ['infertility', 'inability to conceive', 'reproductive failure'],
            'alopecia': ['hair loss', 'baldness', 'hair thinning'],
            'hirsutism': ['excessive hair', 'male pattern hair', 'unwanted hair'],
            'acne': ['pimples', 'blackheads', 'skin eruption', 'comedones'],
            'vitiligo': ['white patches', 'pigment loss', 'depigmentation'],
            'melasma': ['dark patches', 'pregnancy mask', 'hyperpigmentation'],
            'keratosis': ['skin thickening', 'rough patches', 'scaly growth'],
            'mole': ['nevus', 'pigmented lesion', 'skin spot'],
            'wart': ['verruca', 'viral growth', 'skin protrusion'],
            'callus': ['thickened skin', 'hardened area', 'protective buildup'],
            'corn': ['pressure point', 'foot lesion', 'thickened toe skin'],
            'blister': ['fluid bubble', 'vesicle', 'skin separation'],
            'burn': ['thermal injury', 'heat damage', 'tissue destruction'],
            'frostbite': ['cold injury', 'freezing damage', 'tissue freezing'],
            'sunburn': ['UV damage', 'solar injury', 'radiation burn'],
            'rosacea': ['facial redness', 'chronic flushing', 'red nose'],
            'seborrhea': ['oily skin', 'excessive oil', 'greasy scalp'],
            'dandruff': ['scalp flakes', 'seborrheic dermatitis', 'dry scalp'],
            'athlete\'s foot': ['foot fungus', 'tinea pedis', 'fungal infection'],
            'ringworm': ['fungal infection', 'tinea', 'circular rash'],
            'impetigo': ['bacterial skin infection', 'crusty sores', 'honey crust'],
            'herpes simplex': ['cold sores', 'fever blisters', 'viral vesicles'],
            'shingles': ['herpes zoster', 'viral rash', 'painful blisters'],
            'chickenpox': ['varicella', 'childhood disease', 'itchy vesicles'],
            'measles': ['rubeola', 'viral exanthem', 'red rash'],
            'rubella': ['german measles', 'three-day measles', 'mild measles'],
            'mumps': ['parotitis', 'salivary gland swelling', 'jaw swelling'],
            'scarlet fever': ['scarlatina', 'strep rash', 'sandpaper rash'],
            'whooping cough': ['pertussis', 'hundred-day cough', 'spasmodic cough'],
            'diphtheria': ['throat infection', 'membrane formation', 'respiratory obstruction'],
            'tetanus': ['lockjaw', 'muscle spasms', 'trismus'],
            'rabies': ['hydrophobia', 'viral encephalitis', 'mad dog disease'],
            'malaria': ['jungle fever', 'parasitic infection', 'mosquito disease'],
            'dengue': ['breakbone fever', 'viral hemorrhagic fever', 'tropical disease'],
            'yellow fever': ['viral hemorrhagic fever', 'jungle disease', 'tropical fever'],
            'typhoid': ['enteric fever', 'salmonella infection', 'rose spots'],
            'cholera': ['asiatic cholera', 'rice water stools', 'epidemic diarrhea'],
            'dysentery': ['bloody diarrhea', 'infectious colitis', 'inflammatory diarrhea'],
            'food poisoning': ['foodborne illness', 'gastroenteritis', 'toxic ingestion'],
            'botulism': ['food poisoning', 'paralytic illness', 'toxin ingestion'],
            'salmonella': ['food poisoning', 'bacterial gastroenteritis', 'typhoid bacteria'],
            'e.coli': ['bacterial infection', 'hemorrhagic colitis', 'traveler\'s diarrhea'],
            'meningococcal': ['bacterial meningitis', 'epidemic meningitis', 'cerebrospinal fever'],
            'pneumococcal': ['strep pneumonia', 'bacterial pneumonia', 'lung infection'],
            'staphylococcal': ['staph infection', 'golden staph', 'resistant bacteria'],
            'streptococcal': ['strep infection', 'group a strep', 'chain bacteria'],
            'candida': ['yeast infection', 'thrush', 'fungal overgrowth'],
            'aspergillus': ['fungal infection', 'mold infection', 'respiratory fungus'],
            'cryptococcus': ['fungal meningitis', 'yeast infection', 'opportunistic fungus'],
            'histoplasma': ['lung fungus', 'cave disease', 'fungal pneumonia'],
            'blastomyces': ['fungal infection', 'skin fungus', 'systemic mycosis'],
            'coccidioides': ['valley fever', 'desert rheumatism', 'fungal pneumonia'],
            'trichomonas': ['parasitic infection', 'protozoan infection', 'urogenital parasite'],
            'giardia': ['intestinal parasite', 'beaver fever', 'traveler\'s diarrhea'],
            'cryptosporidium': ['intestinal parasite', 'waterborne parasite', 'diarrheal disease'],
            'toxoplasma': ['cat parasite', 'congenital infection', 'brain parasite'],
            'scabies': ['mite infestation', 'itchy rash', 'skin parasites'],
            'lice': ['head lice', 'body lice', 'pubic lice', 'parasitic insects'],
            'bedbugs': ['blood-sucking insects', 'nocturnal parasites', 'apartment pests'],
            'fleas': ['jumping insects', 'pet parasites', 'biting insects'],
            'ticks': ['blood-sucking arachnids', 'disease vectors', 'outdoor parasites'],
            'mosquitoes': ['flying insects', 'disease vectors', 'blood-sucking pests'],
            'altitude sickness': ['mountain sickness', 'hypoxic illness', 'elevation disorder'],
            'motion sickness': ['travel sickness', 'sea sickness', 'car sickness'],
            'jet lag': ['time zone disorder', 'circadian disruption', 'travel fatigue'],
            'hangover': ['alcohol withdrawal', 'morning after', 'ethanol toxicity'],
            'withdrawal': ['substance cessation', 'detoxification symptoms', 'abstinence syndrome'],
            'overdose': ['toxic ingestion', 'drug poisoning', 'excessive consumption'],
            'addiction': ['substance dependence', 'chemical dependency', 'compulsive use'],
            'tolerance': ['drug resistance', 'decreased sensitivity', 'adaptation'],
            'dependence': ['physical reliance', 'withdrawal syndrome', 'habit forming'],
            'intoxication': ['poisoning', 'toxic effects', 'impairment'],
            'side effect': ['adverse reaction', 'unwanted effect', 'medication reaction'],
            
            'anaphylaxis': ['severe allergy', 'life-threatening reaction', 'systemic allergy'],
            'contact dermatitis': ['allergic rash', 'skin reaction', 'contact allergy'],
            'hay fever': ['allergic rhinitis', 'seasonal allergy', 'pollen allergy'],
            'food allergy': ['dietary hypersensitivity', 'food reaction', 'nutritional allergy'],
            'drug allergy': ['medication reaction', 'pharmaceutical hypersensitivity'],
            'latex allergy': ['rubber allergy', 'natural rubber reaction'],
            'bee sting': ['insect sting', 'hymenoptera sting', 'venom reaction'],
            'snake bite': ['venomous bite', 'serpent bite', 'ophidian envenomation'],
            'spider bite': ['arachnid bite', 'venomous bite', 'spider envenomation'],
            'animal bite': ['mammalian bite', 'bite wound', 'puncture wound'],
            'human bite': ['oral trauma', 'bite injury', 'dental trauma'],
            'puncture': ['stab wound', 'penetrating injury', 'pierce'],
            'gunshot': ['ballistic trauma', 'firearm injury', 'penetrating wound'],
            'stabbing': ['knife wound', 'penetrating trauma', 'sharp injury'],
            'blunt trauma': ['non-penetrating injury', 'impact injury', 'crushing force'],
            'whiplash': ['neck injury', 'cervical strain', 'hyperextension injury'],
            'concussion': ['brain injury', 'head trauma', 'mild TBI'],
            'skull fracture': ['cranial fracture', 'head fracture', 'brain case break'],
            'spinal injury': ['back injury', 'vertebral trauma', 'spinal cord damage'],
            'quadriplegia': ['four-limb paralysis', 'tetraplegia', 'complete paralysis'],
            'paraplegia': ['lower body paralysis', 'leg paralysis', 'spinal paralysis'],
            'hemiplegia': ['one-sided paralysis', 'stroke paralysis', 'hemispheric damage'],
            'monoplegia': ['single limb paralysis', 'isolated paralysis', 'one extremity'],
            'diplegia': ['bilateral paralysis', 'two-sided weakness', 'symmetric paralysis'],
            'cerebral palsy': ['brain motor disorder', 'developmental disability', 'movement disorder'],
            'muscular dystrophy': ['muscle wasting disease', 'genetic muscle disorder'],
            'myasthenia gravis': ['muscle weakness disease', 'neuromuscular disorder'],
            'guillain-barre': ['ascending paralysis', 'autoimmune neuropathy'],
            'amyotrophic lateral sclerosis': ['als', 'lou gehrig\'s disease', 'motor neuron disease'],
            'huntington\'s disease': ['hereditary chorea', 'progressive brain disorder'],
            'tourette syndrome': ['tic disorder', 'involuntary movements', 'vocal tics'],
            'autism': ['autism spectrum disorder', 'developmental disorder', 'social communication disorder'],
            'adhd': ['attention deficit hyperactivity disorder', 'hyperactivity disorder'],
            'dyslexia': ['reading disability', 'learning disorder', 'word blindness'],
            'down syndrome': ['trisomy 21', 'mongolism', 'chromosomal disorder'],
            'cystic fibrosis': ['cf', 'mucoviscidosis', 'genetic lung disease'],
            'sickle cell disease': ['sickle cell anemia', 'hemoglobin disorder'],
            'thalassemia': ['mediterranean anemia', 'hemoglobin disorder'],
            'hemophilia': ['bleeding disorder', 'clotting factor deficiency'],
            'von willebrand disease': ['bleeding disorder', 'platelet dysfunction'],
            'thrombophilia': ['clotting disorder', 'hypercoagulable state'],
            'polycythemia': ['high red blood cells', 'thick blood', 'blood viscosity'],
            'leukemia': ['blood cancer', 'white cell cancer', 'hematologic malignancy'],
            'lymphoma': ['lymph node cancer', 'lymphatic cancer', 'hodgkin\'s disease'],
            'myeloma': ['bone marrow cancer', 'plasma cell cancer'],
            'breast cancer': ['mammary carcinoma', 'breast malignancy', 'ductal carcinoma'],
            'lung cancer': ['pulmonary carcinoma', 'bronchogenic carcinoma', 'respiratory cancer'],
            'colon cancer': ['colorectal cancer', 'bowel cancer', 'intestinal cancer'],
            'prostate cancer': ['prostatic carcinoma', 'prostate malignancy'],
            'cervical cancer': ['cervix cancer', 'uterine neck cancer'],
            'ovarian cancer': ['ovary cancer', 'ovarian carcinoma'],
            'testicular cancer': ['testicle cancer', 'testis malignancy'],
            'kidney cancer': ['renal cell carcinoma', 'renal cancer', 'nephroma'],
            'liver cancer': ['hepatocellular carcinoma', 'hepatic cancer', 'hepatoma'],
            'pancreatic cancer': ['pancreas cancer', 'pancreatic carcinoma'],
            'stomach cancer': ['gastric cancer', 'gastric carcinoma'],
            'esophageal cancer': ['esophagus cancer', 'gullet cancer'],
            'bladder cancer': ['urinary bladder cancer', 'urothelial carcinoma'],
            'brain cancer': ['brain tumor', 'cerebral cancer', 'intracranial tumor'],
            'bone cancer': ['osteosarcoma', 'bone tumor', 'skeletal cancer'],
            'skin cancer': ['cutaneous cancer', 'melanoma', 'basal cell carcinoma'],
            'thyroid cancer': ['thyroid carcinoma', 'thyroid tumor'],
            'mesothelioma': ['asbestos cancer', 'pleural cancer', 'lung lining cancer'],
            'sarcoma': ['soft tissue cancer', 'connective tissue cancer'],
            'carcinoma': ['epithelial cancer', 'surface cancer'],
            'adenocarcinoma': ['glandular cancer', 'secretory cancer'],
            'squamous cell carcinoma': ['surface cell cancer', 'skin cancer'],
            'melanoma': ['pigment cancer', 'malignant mole', 'skin cancer'],
            'glioma': ['brain cancer', 'glial cell tumor'],
            'meningioma': ['brain membrane tumor', 'meningeal tumor'],
            'pituitary adenoma': ['pituitary tumor', 'brain gland tumor'],
            'acoustic neuroma': ['hearing nerve tumor', 'vestibular schwannoma'],
            'lipoma': ['fat tumor', 'fatty growth', 'benign fat tumor'],
            'fibroma': ['fibrous tumor', 'connective tissue tumor'],
            'hemangioma': ['blood vessel tumor', 'vascular tumor'],
            'neurofibroma': ['nerve tumor', 'nerve sheath tumor'],
            'myoma': ['muscle tumor', 'uterine fibroid'],
            'adenoma': ['glandular tumor', 'benign gland tumor'],
            'papilloma': ['wart-like tumor', 'surface projection'],
            'keloid': ['raised scar', 'hypertrophic scar', 'excessive scarring'],
            'cheloid': ['overgrown scar', 'fibrous scar'],
            'contracture': ['scar tightening', 'tissue shortening', 'joint limitation'],
            'stricture': ['narrowing', 'constriction', 'passage tightening'],
            'fistula': ['abnormal connection', 'passage between organs'],
            'fasciitis': ['tissue layer infection', 'deep infection', 'necrotizing infection'],
            'septic arthritis': ['joint infection', 'infected joint', 'bacterial arthritis'],
            'endocarditis': ['heart valve infection', 'inner heart infection'],
            'pericarditis': ['heart sac inflammation', 'pericardial inflammation'],
            'myocarditis': ['heart muscle inflammation', 'cardiac muscle infection'],
            'valvulitis': ['heart valve inflammation', 'valve infection'],
            'aortitis': ['aorta inflammation', 'major artery inflammation'],
            'vasculitis': ['blood vessel inflammation', 'arterial inflammation'],
            'phlebitis': ['vein inflammation', 'venous inflammation'],
            'thrombophlebitis': ['clot and inflammation', 'inflamed vein clot'],
            'lymphangitis': ['lymph vessel inflammation', 'lymphatic infection'],
            'lymphadenitis': ['lymph node inflammation', 'swollen glands'],
            'mastitis': ['breast inflammation', 'breast infection'],
            'salpingitis': ['fallopian tube inflammation', 'tube infection'],
            'oophoritis': ['ovary inflammation', 'ovarian infection'],
            'endometritis': ['uterine lining inflammation', 'womb infection'],
            'cervicitis': ['cervix inflammation', 'cervical infection'],
            'vaginitis': ['vagina inflammation', 'vaginal infection'],
            'urethritis': ['urethra inflammation', 'urinary tube infection'],
            'glomerulonephritis': ['kidney filter inflammation', 'glomerular disease'],
            
            'cholangitis': ['bile duct inflammation', 'biliary infection'],
            
            'duodenitis': ['duodenum inflammation', 'small intestine inflammation'],
            'enteritis': ['intestinal inflammation', 'bowel inflammation'],
            
            'proctitis': ['rectum inflammation', 'rectal inflammation'],
           
            'peritonitis': ['abdominal lining inflammation', 'peritoneal infection'],
           
            
            'neuritis': ['nerve inflammation', 'peripheral neuritis'],
            'radiculitis': ['nerve root inflammation', 'spinal nerve inflammation'],
         
            'fibromyalgia': ['widespread pain', 'muscle pain syndrome'],
            'chronic fatigue syndrome': ['cfs', 'systemic exertion intolerance'],
          
            'restless leg syndrome': ['rls', 'leg movement disorder'],
            'sleep apnea': ['breathing interruption', 'sleep breathing disorder'],
           
            'hypersomnia': ['excessive sleep', 'too much sleep'],
            'parasomnia': ['sleep disorder', 'abnormal sleep behavior'],
            'night terrors': ['sleep terror', 'nocturnal fear episodes'],
            'sleepwalking': ['somnambulism', 'sleep walking disorder'],
            'sleep talking': ['somniloquy', 'nocturnal speech'],
            'bruxism': ['teeth grinding', 'jaw clenching', 'nocturnal grinding'],
            'temporomandibular disorder': ['tmd', 'jaw joint disorder', 'tmj'],
            'trigeminal neuralgia': ['facial nerve pain', 'tic douloureux'],
            'bell\'s palsy': ['facial paralysis', 'facial nerve weakness'],
            
            'cubital tunnel syndrome': ['elbow nerve compression', 'ulnar nerve entrapment'],
            'tarsal tunnel syndrome': ['ankle nerve compression', 'posterior tibial entrapment'],
            'thoracic outlet syndrome': ['neck nerve compression', 'brachial plexus compression'],
            'piriformis syndrome': ['hip muscle compression', 'sciatic nerve entrapment'],
            'compartment syndrome': ['muscle compartment pressure', 'limb compression'],
            'complex regional pain syndrome': ['crps', 'reflex sympathetic dystrophy'],
            'phantom limb pain': ['amputee pain', 'missing limb sensation'],
            'diabetic neuropathy': ['diabetes nerve damage', 'diabetic nerve pain'],
            'peripheral neuropathy': ['nerve damage', 'extremity numbness'],
            'autonomic neuropathy': ['automatic nerve damage', 'involuntary nerve dysfunction'],
            'gastroparesis': ['stomach paralysis', 'delayed stomach emptying'],
            'achalasia': ['esophagus motility disorder', 'swallowing disorder'],
            
            'odynophagia': ['painful swallowing', 'swallowing pain'],
            'globus sensation': ['throat fullness', 'lump in throat feeling'],
            'xerostomia': ['dry mouth', 'saliva deficiency'],
            'sialorrhea': ['excessive saliva', 'drooling', 'hypersalivation'],
            'halitosis': ['bad breath', 'oral malodor', 'mouth odor'],
            'gingivitis': ['gum inflammation', 'gum disease'],
            'periodontitis': ['gum infection', 'tooth support loss'],
            'dental caries': ['tooth decay', 'cavities', 'tooth rot'],
            'tooth abscess': ['tooth infection', 'dental infection'],
            'dental erosion': ['tooth wear', 'acid tooth damage'],
            'dental fluorosis': ['fluoride tooth damage', 'mottled teeth'],
            'malocclusion': ['bad bite', 'crooked teeth', 'misaligned teeth'],
            'dental trauma': ['tooth injury', 'dental fracture'],
            'oral thrush': ['mouth yeast infection', 'oral candidiasis'],
            'oral cancer': ['mouth cancer', 'oral cavity cancer'],
            'leukoplakia': ['white mouth patches', 'oral white lesions'],
            'oral lichen planus': ['mouth autoimmune condition', 'oral inflammatory disease']
        }
        
        for token in tokens:
            for key, synonyms in medical_synonyms.items():
                if token in synonyms:
                    expanded_tokens.append(key)
        
        # Try expanded matching
        for token in expanded_tokens:
            proto = self._index.get(token)
            if proto:
                logger.info("Protocol matched", keyword=token, code=proto["protocol_code"])
                return {
                    "protocol_code": proto["protocol_code"],
                    "protocol_text": self._format_protocol(proto),
                }
        
        # Fallback to general protocol
        logger.warning("No NICE protocol match", text=symptom_text)
        return {
            "protocol_code": "GENERAL_TRIAGE", 
            "protocol_text": "General medical triage protocol for symptom assessment"
        }

# --------------------------------------------------------------------------
# Protocol Matching Added 
# --------------------------------------------------------------------------
