"""
NICE Protocol Database Models for Medical Emergency Guidelines
"""
from sqlalchemy import Column, String, Text, JSON, Integer, DateTime, Index
from sqlalchemy.dialects.postgresql import UUID
from uuid import uuid4
from datetime import datetime, timezone
from src.app.core.database import Base

class NICEProtocol(Base):
    """NICE clinical guidelines for emergency triage"""
    __tablename__ = "nice_protocols"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    protocol_code = Column(String(50), nullable=False, unique=True, index=True)
    condition_name = Column(String(200), nullable=False, index=True)
    
    # Symptom mapping
    primary_symptoms = Column(JSON, nullable=False)  # ["headache", "chest_pain"]
    red_flag_symptoms = Column(JSON, nullable=False)  # Emergency indicators
    
    # Questioning strategy
    initial_questions = Column(JSON, nullable=False)  # First questions to ask
    follow_up_questions = Column(JSON, nullable=False)  # Progressive questions
    
    # Decision pathways
    emergency_criteria = Column(Text, nullable=False)  # When to route to emergency
    routine_criteria = Column(Text, nullable=False)    # When routine doctor visit
    self_care_criteria = Column(Text, nullable=False)  # When self-care appropriate
    
    # Metadata
    evidence_level = Column(String(10), nullable=False)  # A, B, C evidence quality
    last_updated = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    
    # Database indexes for fast lookup
    __table_args__ = (
        Index('idx_nice_symptoms', 'primary_symptoms'),
        Index('idx_nice_condition', 'condition_name'),
    )

"""
nice_fhir_seed.py
-----------------
Seed data for 50 NICE-aligned emergency protocols, grouped into 5 categories
(10 per category) with basic FHIR Condition codes.
Each dictionary is kept on a single line so the file stays <200 LOC.
"""

NICE_SEED_DATA = [
 # ---------------------- CARDIOVASCULAR (10) ----------------------
 {"protocol_code" : "CG95_CHEST_PAIN" , "category" : "Cardiovascular" , "condition_name" : "Chest Pain Assessment" , "primary_symptoms" : ["chest_pain" , "chest_discomfort"] , "red_flag_symptoms" : ["radiating_pain" , "sweating" , "dyspnea"] , "initial_questions" : ["Describe the chest pain quality and location." , "Does activity change the pain?" , "Any nausea or sweating?"] , "follow_up_questions" : ["History of heart disease?" , "Risk factors like diabetes or smoking?" , "Relief with nitrates?"] , "emergency_criteria" : "Crushing central pain >20 min with red flags" , "routine_criteria" : "Atypical pain, stable vitals" , "self_care_criteria" : "Musculoskeletal pain reproducible on palpation" , "evidence_level" : "A" , "fhir_code" : "29857009"},
 {"protocol_code" : "NG136_MI" , "category" : "Cardiovascular" , "condition_name" : "Acute Myocardial Infarction" , "primary_symptoms" : ["severe_chest_pain" , "diaphoresis"] , "red_flag_symptoms" : ["hypotension" , "syncope" , "arrhythmia"] , "initial_questions" : ["When did pain start?" , "Any SOB or sweating?" , "Previous MI?"] , "follow_up_questions" : ["Nitroglycerin response?" , "Family cardiac history?" , "Current meds?"] , "emergency_criteria" : "ST-elevation or troponin rise with symptoms" , "routine_criteria" : "Resolved pain, normal biomarkers" , "self_care_criteria" : "None – always clinician review" , "evidence_level" : "A" , "fhir_code" : "22298006"},
 {"protocol_code" : "CG14_UNSTABLE_ANGINA" , "category" : "Cardiovascular" , "condition_name" : "Unstable Angina" , "primary_symptoms" : ["rest_chest_pain"] , "red_flag_symptoms" : ["new_onset_angina" , "increasing_frequency"] , "initial_questions" : ["Is pain occurring at rest?" , "How long does it last?" , "Any radiation?"] , "follow_up_questions" : ["Risk factors?" , "Aspirin taken?" , "Previous stents?"] , "emergency_criteria" : "New rest pain <24 h or crescendo pattern" , "routine_criteria" : "Stable exertional pattern" , "self_care_criteria" : "None – specialist follow-up" , "evidence_level" : "A" , "fhir_code" : "413444003"},
 {"protocol_code" : "PE_EMERGENCY" , "category" : "Cardiovascular" , "condition_name" : "Pulmonary Embolism" , "primary_symptoms" : ["pleuritic_pain" , "sudden_dyspnea"] , "red_flag_symptoms" : ["collapse" , "hypoxia"] , "initial_questions" : ["Onset of breathlessness?" , "Recent travel/surgery?" , "Leg swelling?"] , "follow_up_questions" : ["Cancer history?" , "Hormonal therapy?" , "Prior clots?"] , "emergency_criteria" : "Shock or SpO₂<90 % with suspected PE" , "routine_criteria" : "Low Wells score, stable vitals" , "self_care_criteria" : "None – imaging required" , "evidence_level" : "A" , "fhir_code" : "59282003"},
 {"protocol_code" : "NG17_AORTIC_DISSECTION" , "category" : "Cardiovascular" , "condition_name" : "Aortic Dissection" , "primary_symptoms" : ["tearing_chest_pain" , "back_pain"] , "red_flag_symptoms" : ["pulse_deficit" , "neurological_deficit"] , "initial_questions" : ["Describe pain character." , "Radiation to back?" , "Known aneurysm?"] , "follow_up_questions" : ["Marfan features?" , "Hypertension history?" , "Trauma?"] , "emergency_criteria" : "Sudden tearing pain plus unequal BP" , "routine_criteria" : "Stable chronic dissection on imaging" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "233985008"},
 {"protocol_code" : "NG106_ACUTE_HF" , "category" : "Cardiovascular" , "condition_name" : "Acute Heart Failure" , "primary_symptoms" : ["orthopnea" , "paroxysmal_nocturnal_dyspnea"] , "red_flag_symptoms" : ["pulmonary_edema" , "hypotension"] , "initial_questions" : ["How many pillows at night?" , "Leg swelling?" , "Weight gain?"] , "follow_up_questions" : ["Known EF?" , "Recent MI?" , "Alcohol intake?"] , "emergency_criteria" : "Respiratory distress or SpO₂<90 %" , "routine_criteria" : "Mild edema responsive to diuretics" , "self_care_criteria" : "Lifestyle optimization" , "evidence_level" : "A" , "fhir_code" : "84114007"},
 {"protocol_code" : "CG94_VTACH" , "category" : "Cardiovascular" , "condition_name" : "Ventricular Tachycardia" , "primary_symptoms" : ["palpitations" , "dizziness"] , "red_flag_symptoms" : ["syncope" , "hemodynamic_instability"] , "initial_questions" : ["Palpitations onset?" , "Chest pain?" , "Implanted ICD?"] , "follow_up_questions" : ["Electrolyte issues?" , "Drug triggers?" , "Family SCD?"] , "emergency_criteria" : "Sustained VT with instability" , "routine_criteria" : "Non-sustained, asymptomatic" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "426644000"},
 {"protocol_code" : "NG74_CARDIAC_TAMPONADE" , "category" : "Cardiovascular" , "condition_name" : "Cardiac Tamponade" , "primary_symptoms" : ["progressive_dyspnea" , "chest_pressure"] , "red_flag_symptoms" : ["muffled_heart_sounds" , "pulsus_paradoxus"] , "initial_questions" : ["Recent pericarditis?" , "Trauma history?" , "Cancer?"] , "follow_up_questions" : ["Anticoagulation use?" , "Autoimmune disease?" , "Dialysis?"] , "emergency_criteria" : "Beck’s triad with shock" , "routine_criteria" : "Small pericardial effusion, stable" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "422623009"},
 {"protocol_code" : "NG136_HTN_CRISIS" , "category" : "Cardiovascular" , "condition_name" : "Hypertensive Emergency" , "primary_symptoms" : ["severe_headache" , "visual_disturbance"] , "red_flag_symptoms" : ["BP>180/120" , "end_organ_damage"] , "initial_questions" : ["Known HTN?" , "Medication adherence?" , "Neurological symptoms?"] , "follow_up_questions" : ["Chest pain?" , "Kidney disease?" , "Pregnancy?"] , "emergency_criteria" : "Acute target-organ damage with BP crisis" , "routine_criteria" : "Asymptomatic severe HTN" , "self_care_criteria" : "Lifestyle measures for stage-1 HTN" , "evidence_level" : "A" , "fhir_code" : "5204005"},
 {"protocol_code" : "NG87_CARDIOGENIC_SHOCK" , "category" : "Cardiovascular" , "condition_name" : "Cardiogenic Shock" , "primary_symptoms" : ["cold_clammy_skin" , "oliguria"] , "red_flag_symptoms" : ["SBP<90" , "altered_mental_status"] , "initial_questions" : ["Chest pain preceding?" , "Fluid intake?" , "Arrhythmias?"] , "follow_up_questions" : ["Echo available?" , "MI care?" , "Renal function?"] , "emergency_criteria" : "Low BP with signs of hypoperfusion" , "routine_criteria" : "Compensated low EF without shock" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "705981003"},

 # ---------------------- RESPIRATORY (10) ----------------------
 {"protocol_code" : "NG80_ASTHMA_EXAC" , "category" : "Respiratory" , "condition_name" : "Acute Severe Asthma" , "primary_symptoms" : ["wheeze" , "dyspnea"] , "red_flag_symptoms" : ["silent_chest" , "exhaustion"] , "initial_questions" : ["Inhaler use today?" , "Peak flow reading?" , "Previous ICU admissions?"] , "follow_up_questions" : ["Trigger exposure?" , "Steroid use?" , "Allergies?"] , "emergency_criteria" : "PEF<50 % or SpO₂<92 %" , "routine_criteria" : "Mild attack responsive to bronchodilator" , "self_care_criteria" : "Controlled asthma with action plan" , "evidence_level" : "A" , "fhir_code" : "195967001"},
 {"protocol_code" : "COPD_EXAC" , "category" : "Respiratory" , "condition_name" : "COPD Exacerbation" , "primary_symptoms" : ["increased_dyspnea" , "productive_cough"] , "red_flag_symptoms" : ["cyanosis" , "confusion"] , "initial_questions" : ["Sputum color change?" , "Home oxygen?" , "Smoking status?"] , "follow_up_questions" : ["Prev hospitalizations?" , "Vaccination status?" , "Steroid courses?"] , "emergency_criteria" : "Severe dyspnea or acidosis" , "routine_criteria" : "Moderate exacerbation, stable sats" , "self_care_criteria" : "Mild increase in symptoms managed at home" , "evidence_level" : "B" , "fhir_code" : "116289008"},
 {"protocol_code" : "PULM_EDEMA" , "category" : "Respiratory" , "condition_name" : "Acute Pulmonary Edema" , "primary_symptoms" : ["pink_frothy_sputum" , "orthopnea"] , "red_flag_symptoms" : ["severe_hypoxia" , "crackles_all_zones"] , "initial_questions" : ["Onset of symptoms?" , "Chest pain?" , "Hypertension history?"] , "follow_up_questions" : ["Medication compliance?" , "Renal issues?" , "Alcohol intake?"] , "emergency_criteria" : "Resp distress with hypoxia despite O₂" , "routine_criteria" : "Mild edema responsive to diuretics" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "59621000"},
 {"protocol_code" : "TENSION_PT" , "category" : "Respiratory" , "condition_name" : "Tension Pneumothorax" , "primary_symptoms" : ["sudden_chest_pain" , "dyspnea"] , "red_flag_symptoms" : ["tracheal_deviation" , "absent_breath_sounds"] , "initial_questions" : ["Trauma?" , "COPD bullae?" , "Procedures?"] , "follow_up_questions" : ["Previous pneumothorax?" , "Smoking?" , "Connective tissue disease?"] , "emergency_criteria" : "Hemodynamic compromise with unilateral hyperresonance" , "routine_criteria" : "Small stable pneumothorax" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "68270000"},
 {"protocol_code" : "HEMOTHORAX" , "category" : "Respiratory" , "condition_name" : "Massive Hemothorax" , "primary_symptoms" : ["chest_fullness" , "dyspnea"] , "red_flag_symptoms" : ["shock" , "dullness_to_percussion"] , "initial_questions" : ["Trauma details?" , "Anticoagulant use?" , "Breathlessness severity?"] , "follow_up_questions" : ["Allergies?" , "Prior thoracic surgery?" , "Blood type known?"] , "emergency_criteria" : ">1.5 L blood loss or shock" , "routine_criteria" : "Small, non-progressive collection" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "422400008"},
 {"protocol_code" : "SEV_PNEUMONIA" , "category" : "Respiratory" , "condition_name" : "Severe Community-Acquired Pneumonia" , "primary_symptoms" : ["fever" , "productive_cough"] , "red_flag_symptoms" : ["SpO₂<90" , "confusion"] , "initial_questions" : ["Duration of symptoms?" , "Vaccinations?" , "Travel history?"] , "follow_up_questions" : ["Comorbidities?" , "Smoking?" , "Antibiotic allergies?"] , "emergency_criteria" : "CURB-65≥3 or sepsis" , "routine_criteria" : "Mild pneumonia outpatient" , "self_care_criteria" : "Viral URI" , "evidence_level" : "A" , "fhir_code" : "233604007"},
 {"protocol_code" : "FBAO" , "category" : "Respiratory" , "condition_name" : "Foreign Body Airway Obstruction" , "primary_symptoms" : ["sudden_cough" , "inability_to_speak"] , "red_flag_symptoms" : ["cyanosis" , "collapse"] , "initial_questions" : ["What was ingested?" , "Onset time?" , "Attempts to clear?"] , "follow_up_questions" : ["Witnessed choking?" , "Underlying dysphagia?" , "CPR performed?"] , "emergency_criteria" : "Partial or complete obstruction compromising airway" , "routine_criteria" : "Resolved obstruction, no symptoms" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "86049000"},
 {"protocol_code" : "ARDS" , "category" : "Respiratory" , "condition_name" : "Acute Respiratory Distress Syndrome" , "primary_symptoms" : ["severe_dyspnea" , "tachypnea"] , "red_flag_symptoms" : ["refractory_hypoxemia" , "bilateral_infiltrates"] , "initial_questions" : ["Trigger event?" , "Sepsis signs?" , "Smoke inhalation?"] , "follow_up_questions" : ["Fluid balance?" , "Ventilation history?" , "Comorbidities?"] , "emergency_criteria" : "PaO₂/FiO₂<200 with bilateral opacities" , "routine_criteria" : "ALI criteria but stable" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "67782005"},
 {"protocol_code" : "ANAPHYLAXIS_AIRWAY" , "category" : "Respiratory" , "condition_name" : "Anaphylaxis with Airway Compromise" , "primary_symptoms" : ["stridor" , "facial_swelling"] , "red_flag_symptoms" : ["hypotension" , "collapse"] , "initial_questions" : ["Allergen exposure?" , "Epi-pen used?" , "Previous reactions?"] , "follow_up_questions" : ["Asthma history?" , "β-blocker use?" , "Mastocytosis?"] , "emergency_criteria" : "Airway edema or shock" , "routine_criteria" : "Mild urticaria only" , "self_care_criteria" : "Allergen avoidance education" , "evidence_level" : "A" , "fhir_code" : "39579001"},
 {"protocol_code" : "COVID_SEVERE" , "category" : "Respiratory" , "condition_name" : "Severe COVID-19 Pneumonia" , "primary_symptoms" : ["fever" , "cough" , "dyspnea"] , "red_flag_symptoms" : ["SpO₂<92" , "tachypnea>30"] , "initial_questions" : ["Vaccination status?" , "Onset date?" , "Home oximetry readings?"] , "follow_up_questions" : ["Comorbidities?" , "Steroid started?" , "Contact tracing?"] , "emergency_criteria" : "Severe hypoxia or respiratory failure" , "routine_criteria" : "Mild disease managed at home" , "self_care_criteria" : "Isolation and monitoring" , "evidence_level" : "B" , "fhir_code" : "840539006"},

 # ---------------------- NEUROLOGICAL (10) ----------------------
 {"protocol_code" : "NG127_HEADACHE" , "category" : "Neurological" , "condition_name" : "Headache Assessment" , "primary_symptoms" : ["headache" , "photophobia"] , "red_flag_symptoms" : ["thunderclap" , "neck_stiffness"] , "initial_questions" : ["Pain location and quality?" , "Onset time?" , "Associated nausea?"] , "follow_up_questions" : ["Worst ever headache?" , "Neck stiffness?" , "Recent trauma?"] , "emergency_criteria" : "Sudden worst headache, neuro deficit" , "routine_criteria" : "Tension headache pattern" , "self_care_criteria" : "Known migraine responsive to OTC" , "evidence_level" : "A" , "fhir_code" : "25064002"},
 {"protocol_code" : "ISCHEMIC_STROKE" , "category" : "Neurological" , "condition_name" : "Acute Ischemic Stroke" , "primary_symptoms" : ["unilateral_weakness" , "speech_difficulty"] , "red_flag_symptoms" : ["facial_droop" , "gaze_palsy"] , "initial_questions" : ["Last known well?" , "Anticoagulant use?" , "Onset witnessed?"] , "follow_up_questions" : ["Hypertension history?" , "Glucose level?" , "Previous stroke?"] , "emergency_criteria" : "Onset <4.5 h with deficits" , "routine_criteria" : "TIA resolved" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "44054006"},
 {"protocol_code" : "ICH" , "category" : "Neurological" , "condition_name" : "Intracerebral Hemorrhage" , "primary_symptoms" : ["sudden_headache" , "hemiparesis"] , "red_flag_symptoms" : ["vomiting" , "decreased_consciousness"] , "initial_questions" : ["Anticoagulant use?" , "Trauma?" , "Hypertension?"] , "follow_up_questions" : ["Alcohol abuse?" , "Previous ICH?" , "Seizure?"] , "emergency_criteria" : "Acute neuro deficit with high BP" , "routine_criteria" : "Chronic small bleed, stable" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "274100004"},
 {"protocol_code" : "SAH" , "category" : "Neurological" , "condition_name" : "Subarachnoid Hemorrhage" , "primary_symptoms" : ["thunderclap_headache" , "photophobia"] , "red_flag_symptoms" : ["neck_stiffness" , "collapse"] , "initial_questions" : ["Worst headache ever?" , "Syncope?" , "Drug use?"] , "follow_up_questions" : ["Family aneurysm?" , "Hypertension?" , "Vomiting?"] , "emergency_criteria" : "Thunderclap headache ± neuro signs" , "routine_criteria" : "Resolved headache, normal CT" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "233963000"},
 {"protocol_code" : "STATUS_EPI" , "category" : "Neurological" , "condition_name" : "Status Epilepticus" , "primary_symptoms" : ["continuous_seizure" , "unconsciousness"] , "red_flag_symptoms" : ["cyanosis" , "hypoxia"] , "initial_questions" : ["Duration of seizure?" , "Anti-seizure meds adherence?" , "Alcohol withdrawal?"] , "follow_up_questions" : ["Head trauma?" , "Infection?" , "Pregnancy?"] , "emergency_criteria" : ">5 min seizure or recurrent w/o recovery" , "routine_criteria" : "Brief self-limited seizure" , "self_care_criteria" : "Medication compliance counseling" , "evidence_level" : "A" , "fhir_code" : "230711007"},
 {"protocol_code" : "MENINGITIS_ACUTE" , "category" : "Neurological" , "condition_name" : "Acute Bacterial Meningitis" , "primary_symptoms" : ["fever" , "neck_stiffness"] , "red_flag_symptoms" : ["photophobia" , "petichial_rash"] , "initial_questions" : ["Onset of fever?" , "Vaccination status?" , "Seizures?"] , "follow_up_questions" : ["Recent URTI?" , "Immunocompromised?" , "Travel?"] , "emergency_criteria" : "Sepsis signs or neuro deficit" , "routine_criteria" : "Viral meningitis suspicion" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "7180009"},
 {"protocol_code" : "GBS" , "category" : "Neurological" , "condition_name" : "Guillain-Barré Syndrome" , "primary_symptoms" : ["ascending_weakness" , "paresthesia"] , "red_flag_symptoms" : ["respiratory_muscle_weakness" , "autonomic_instability"] , "initial_questions" : ["Onset after infection?" , "Vaccinations?" , "Walking ability?"] , "follow_up_questions" : ["Facial weakness?" , "Bulbar symptoms?" , "Pain?"] , "emergency_criteria" : "Rapid progression <4 h or FVC<20 mL/kg" , "routine_criteria" : "Slow progression, ambulatory" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "40956001"},
 {"protocol_code" : "TBI_SEVERE" , "category" : "Neurological" , "condition_name" : "Severe Traumatic Brain Injury" , "primary_symptoms" : ["loss_of_consciousness" , "vomiting"] , "red_flag_symptoms" : ["GCS<8" , "pupil_asymmetry"] , "initial_questions" : ["Mechanism of injury?" , "Helmet worn?" , "Seizure?"] , "follow_up_questions" : ["Anticoagulant?" , "Alcohol?" , "Previous TBI?"] , "emergency_criteria" : "GCS<9 or neuro deficit" , "routine_criteria" : "Mild concussion" , "self_care_criteria" : "Return-to-play advice" , "evidence_level" : "A" , "fhir_code" : "86299005"},
 {"protocol_code" : "SPINAL_COMP" , "category" : "Neurological" , "condition_name" : "Spinal Cord Compression" , "primary_symptoms" : ["back_pain" , "weakness"] , "red_flag_symptoms" : ["bladder_retention" , "saddle_anesthesia"] , "initial_questions" : ["Cancer history?" , "Trauma?" , "Onset speed?"] , "follow_up_questions" : ["Steroid use?" , "Chemotherapy?" , "Radiation?"] , "emergency_criteria" : "Neurological deficit with compression signs" , "routine_criteria" : "Chronic pain without deficit" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "74306000"},
 {"protocol_code" : "MYASTHENIC_CRISIS" , "category" : "Neurological" , "condition_name" : "Myasthenic Crisis" , "primary_symptoms" : ["respiratory_weakness" , "ptosis"] , "red_flag_symptoms" : ["hypercapnia" , "bulbar_dysfunction"] , "initial_questions" : ["Medication compliance?" , "Infection?" , "Recent surgery?"] , "follow_up_questions" : ["Thymectomy?" , "Autoimmune disorders?" , "Drug triggers?"] , "emergency_criteria" : "Need for ventilatory support" , "routine_criteria" : "Mild weakness responsive to meds" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "91936005"},

 # ---------------------- GASTROINTESTINAL (10) ----------------------
 {"protocol_code" : "ACUTE_PANCREATITIS" , "category" : "Gastrointestinal" , "condition_name" : "Acute Pancreatitis" , "primary_symptoms" : ["epigastric_pain" , "vomiting"] , "red_flag_symptoms" : ["hypotension" , "hypocalcemia"] , "initial_questions" : ["Alcohol intake?" , "Gallstones?" , "Pain radiation?"] , "follow_up_questions" : ["Lipase done?" , "Previous attacks?" , "Drug triggers?"] , "emergency_criteria" : "Severe pancreatitis with organ failure" , "routine_criteria" : "Mild pancreatitis, tolerating oral" , "self_care_criteria" : "Dietary advice post-episode" , "evidence_level" : "A" , "fhir_code" : "235719002"},
 {"protocol_code" : "PERF_ULCER" , "category" : "Gastrointestinal" , "condition_name" : "Perforated Peptic Ulcer" , "primary_symptoms" : ["sudden_epigastric_pain" , "rigid_abdomen"] , "red_flag_symptoms" : ["peritonitis" , "shock"] , "initial_questions" : ["NSAID use?" , "H. pylori?" , "Previous ulcer?"] , "follow_up_questions" : ["Alcohol?" , "Steroids?" , "Anticoagulants?"] , "emergency_criteria" : "Free air under diaphragm + peritonitis" , "routine_criteria" : "Ulcer pain without perforation" , "self_care_criteria" : "PPI therapy lifestyle" , "evidence_level" : "A" , "fhir_code" : "191233003"},
 {"protocol_code" : "VARICEAL_BLEED" , "category" : "Gastrointestinal" , "condition_name" : "Variceal Upper GI Bleed" , "primary_symptoms" : ["hematemesis" , "melena"] , "red_flag_symptoms" : ["hypotension" , "tachycardia"] , "initial_questions" : ["Liver disease history?" , "Alcohol?" , "Volume of blood?"] , "follow_up_questions" : ["Beta-blocker use?" , "Recent endoscopy?" , "Encephalopathy?"] , "emergency_criteria" : "Active bleeding with shock" , "routine_criteria" : "Portal hypertension but no bleed" , "self_care_criteria" : "Abstinence counseling" , "evidence_level" : "A" , "fhir_code" : "87600003"},
 {"protocol_code" : "MESENTERIC_ISCHEMIA" , "category" : "Gastrointestinal" , "condition_name" : "Acute Mesenteric Ischemia" , "primary_symptoms" : ["severe_abdominal_pain" , "out_of_proportion_pain"] , "red_flag_symptoms" : ["bloody_stools" , "peritonitis"] , "initial_questions" : ["AFib history?" , "Weight loss?" , "Pain after eating?"] , "follow_up_questions" : ["Smoking?" , "Vascular disease?" , "D-dimer?"] , "emergency_criteria" : "CT angiography showing occlusion" , "routine_criteria" : "Chronic ischemia, stable" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "71444005"},
 {"protocol_code" : "BOWEL_OBSTRUCTION" , "category" : "Gastrointestinal" , "condition_name" : "Small Bowel Obstruction" , "primary_symptoms" : ["colicky_pain" , "vomiting"] , "red_flag_symptoms" : ["peritonitis" , "strangulation"] , "initial_questions" : ["Previous surgeries?" , "Hernias?" , "Onset of distension?"] , "follow_up_questions" : ["Flatus passed?" , "Fever?" , "CT scan?"] , "emergency_criteria" : "Strangulated obstruction or peritonitis" , "routine_criteria" : "Partial obstruction responsive to NG" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "5602001"},
 {"protocol_code" : "APPENDICITIS_PERF" , "category" : "Gastrointestinal" , "condition_name" : "Perforated Appendicitis" , "primary_symptoms" : ["right_lower_quad_pain" , "fever"] , "red_flag_symptoms" : ["guarding" , "rebound_tenderness"] , "initial_questions" : ["Pain migration?" , "Nausea?" , "Loss of appetite?"] , "follow_up_questions" : ["Pregnancy?" , "Previous episodes?" , "CT findings?"] , "emergency_criteria" : "Peritonitis or abscess" , "routine_criteria" : "Uncomplicated early appendicitis" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "62413002"},
 {"protocol_code" : "CHOLECYSTITIS_SEPSIS" , "category" : "Gastrointestinal" , "condition_name" : "Acute Cholecystitis with Sepsis" , "primary_symptoms" : ["RUQ_pain" , "fever"] , "red_flag_symptoms" : ["jaundice" , "hypotension"] , "initial_questions" : ["Gallstone history?" , "Vomiting?" , "Murphy sign?"] , "follow_up_questions" : ["Antibiotic allergies?" , "Diabetes?" , "Pregnancy?"] , "emergency_criteria" : "Sepsis or gallbladder perforation" , "routine_criteria" : "Biliary colic only" , "self_care_criteria" : "Dietary fat reduction" , "evidence_level" : "A" , "fhir_code" : "235595009"},
 {"protocol_code" : "BOERHAAVE" , "category" : "Gastrointestinal" , "condition_name" : "Esophageal Rupture" , "primary_symptoms" : ["severe_chest_pain" , "subcutaneous_emphysema"] , "red_flag_symptoms" : ["shock" , "hematemesis"] , "initial_questions" : ["Forceful vomiting?" , "Alcohol binge?" , "Swallowing foreign body?"] , "follow_up_questions" : ["Endoscopy?" , "Mediastinitis signs?" , "Pleural effusion?"] , "emergency_criteria" : "CT confirming perforation" , "routine_criteria" : "Mallory-Weiss tear" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "109838007"},
 {"protocol_code" : "ACUTE_LIVER_FAILURE" , "category" : "Gastrointestinal" , "condition_name" : "Acute Liver Failure" , "primary_symptoms" : ["jaundice" , "altered_mental_status"] , "red_flag_symptoms" : ["coagulopathy" , "cerebral_edema"] , "initial_questions" : ["Paracetamol overdose?" , "Viral hepatitis risk?" , "Drug history?"] , "follow_up_questions" : ["INR value?" , "Ammonia level?" , "Renal function?"] , "emergency_criteria" : "INR>1.5 with encephalopathy" , "routine_criteria" : "Compensated cirrhosis" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "197315008"},
 {"protocol_code" : "DIVERTICULAR_PERF" , "category" : "Gastrointestinal" , "condition_name" : "Perforated Diverticulitis" , "primary_symptoms" : ["left_lower_quad_pain" , "fever"] , "red_flag_symptoms" : ["peritonitis" , "abscess"] , "initial_questions" : ["Previous episodes?" , "Bowel habits?" , "Antibiotic use?"] , "follow_up_questions" : ["CT findings?" , "Immunosuppression?" , "Bleeding?"] , "emergency_criteria" : "Free perforation with sepsis" , "routine_criteria" : "Uncomplicated diverticulitis" , "self_care_criteria" : "High-fiber diet advice" , "evidence_level" : "B" , "fhir_code" : "27550009"},

 # ---------------------- TRAUMA (10) ----------------------
 {"protocol_code" : "POLYTRAUMA" , "category" : "Trauma" , "condition_name" : "Polytrauma" , "primary_symptoms" : ["multiple_injuries" , "hypotension"] , "red_flag_symptoms" : ["GCS<8" , "SBP<90"] , "initial_questions" : ["Mechanism of injury?" , "Time since incident?" , "Protective gear?"] , "follow_up_questions" : ["Allergies?" , "Anticoagulants?" , "Last meal?"] , "emergency_criteria" : "ABC compromise or shock" , "routine_criteria" : "Minor injuries only" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "444972004"},
 {"protocol_code" : "PEN_ABD_TRAUMA" , "category" : "Trauma" , "condition_name" : "Penetrating Abdominal Trauma" , "primary_symptoms" : ["abdominal_pain" , "external_bleeding"] , "red_flag_symptoms" : ["evisceration" , "peritonitis"] , "initial_questions" : ["Weapon type?" , "Entry/exit wounds?" , "Pain level?"] , "follow_up_questions" : ["Tetanus status?" , "FAST scan?" , "Hemoglobin?"] , "emergency_criteria" : "Peritonitis or hemodynamic instability" , "routine_criteria" : "Superficial wound only" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "125666000"},
 {"protocol_code" : "PELVIC_FRAC" , "category" : "Trauma" , "condition_name" : "Pelvic Fracture with Hemorrhage" , "primary_symptoms" : ["pelvic_pain" , "inability_to_bear_weight"] , "red_flag_symptoms" : ["hypotension" , "urethral_bleed"] , "initial_questions" : ["High-energy impact?" , "Hematuria?" , "Leg length discrepancy?"] , "follow_up_questions" : ["IV access?" , "Pelvic binder applied?" , "CT angiography?"] , "emergency_criteria" : "Shock or open fracture" , "routine_criteria" : "Stable pubic rami fracture" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "239873007"},
 {"protocol_code" : "OPEN_LONG_BONE" , "category" : "Trauma" , "condition_name" : "Open Long-Bone Fracture" , "primary_symptoms" : ["visible_bone" , "severe_pain"] , "red_flag_symptoms" : ["neurovascular_deficit" , "compartment_syndrome"] , "initial_questions" : ["Mechanism?" , "Contamination?" , "Tetanus status?"] , "follow_up_questions" : ["Analgesia given?" , "Splint applied?" , "Bleeding control?"] , "emergency_criteria" : "Open fracture Gustilo III or NV deficit" , "routine_criteria" : "Closed fracture" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "263195009"},
 {"protocol_code" : "SUS_SPINAL_INJ" , "category" : "Trauma" , "condition_name" : "Suspected Spinal Injury" , "primary_symptoms" : ["neck_pain" , "numbness"] , "red_flag_symptoms" : ["paralysis" , "priapism"] , "initial_questions" : ["High-risk mechanism?" , "Pain location?" , "Weakness?"] , "follow_up_questions" : ["Immobilization done?" , "Sensory exam?" , "Rectal tone?"] , "emergency_criteria" : "Neuro deficit or unstable fracture" , "routine_criteria" : "Whiplash without neuro signs" , "self_care_criteria" : "Posture education" , "evidence_level" : "A" , "fhir_code" : "125605004"},
 {"protocol_code" : "CRUSH_RHABDO" , "category" : "Trauma" , "condition_name" : "Crush Injury with Rhabdomyolysis" , "primary_symptoms" : ["limb_swelling" , "pain"] , "red_flag_symptoms" : ["dark_urine" , "hyperkalemia"] , "initial_questions" : ["Duration of entrapment?" , "Urine color?" , "Pain severity?"] , "follow_up_questions" : ["CK level?" , "Renal function?" , "Fluid resuscitation?"] , "emergency_criteria" : "Hyperkalemia or CK>5000" , "routine_criteria" : "Minor soft-tissue injury" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "225566009"},
 {"protocol_code" : "SEV_BURN" , "category" : "Trauma" , "condition_name" : "Severe Burn >30 % TBSA" , "primary_symptoms" : ["pain" , "blistering"] , "red_flag_symptoms" : ["inhalation_injury" , "hypovolemia"] , "initial_questions" : ["Cause of burn?" , "TBSA estimate?" , "Enclosed space?"] , "follow_up_questions" : ["Tetanus?" , "Fluid formula?" , "Analgesia?"] , "emergency_criteria" : ">30 % TBSA or circumferential burns" , "routine_criteria" : "Minor partial-thickness burn" , "self_care_criteria" : "Topical care for <5 % burn" , "evidence_level" : "A" , "fhir_code" : "49550006"},
 {"protocol_code" : "TRAUM_AMP" , "category" : "Trauma" , "condition_name" : "Traumatic Amputation" , "primary_symptoms" : ["limb_loss" , "hemorrhage"] , "red_flag_symptoms" : ["hypotension" , "shock"] , "initial_questions" : ["Time of amputation?" , "Part preserved?" , "Mechanism?"] , "follow_up_questions" : ["Tourniquet applied?" , "IV fluids?" , "Tetanus?"] , "emergency_criteria" : "Major limb loss with bleeding" , "routine_criteria" : "Distal fingertip only" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "702958008"},
 {"protocol_code" : "COMP_SYNDROME" , "category" : "Trauma" , "condition_name" : "Acute Compartment Syndrome" , "primary_symptoms" : ["severe_pain_out_of_proportion" , "paresthesia"] , "red_flag_symptoms" : ["pulselessness" , "paralysis"] , "initial_questions" : ["Pain with passive stretch?" , "Mechanism?" , "Analgesia response?"] , "follow_up_questions" : ["Pressure measurement?" , "Anticoagulants?" , "Swelling onset?"] , "emergency_criteria" : "Compartment pressure >30 mmHg" , "routine_criteria" : "Bruising without tight compartment" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "70211007"},
 {"protocol_code" : "TRAUMATIC_PT" , "category" : "Trauma" , "condition_name" : "Traumatic Pneumothorax" , "primary_symptoms" : ["chest_pain" , "dyspnea"] , "red_flag_symptoms" : ["hypotension" , "respiratory_distress"] , "initial_questions" : ["Blunt vs penetrating?" , "Dyspnea severity?" , "LOC?"] , "follow_up_questions" : ["FAST exam?" , "Chest wall deformity?" , "Analgesia?"] , "emergency_criteria" : "Large pneumothorax with distress" , "routine_criteria" : "Small asymptomatic PTX" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "233978006"}
]
