"""
NICE Protocol Database Models for Medical Emergency Guidelines
"""
from sqlalchemy import Column, String, Text, JSON, Integer, DateTime, Index
from sqlalchemy.dialects.postgresql import UUID
from uuid import uuid4
from datetime import datetime, timezone
from src.app.core.database import Base

class NICEProtocol(Base):
    """NICE clinical guidelines for emergency triage"""
    __tablename__ = "nice_protocols"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    protocol_code = Column(String(50), nullable=False, unique=True, index=True)
    condition_name = Column(String(200), nullable=False, index=True)
    
    # Symptom mapping
    primary_symptoms = Column(JSON, nullable=False)  # ["headache", "chest_pain"]
    red_flag_symptoms = Column(JSON, nullable=False)  # Emergency indicators
    
    # Questioning strategy
    initial_questions = Column(JSON, nullable=False)  # First questions to ask
    follow_up_questions = Column(JSON, nullable=False)  # Progressive questions
    
    # Decision pathways
    emergency_criteria = Column(Text, nullable=False)  # When to route to emergency
    routine_criteria = Column(Text, nullable=False)    # When routine doctor visit
    self_care_criteria = Column(Text, nullable=False)  # When self-care appropriate
    
    # Metadata
    evidence_level = Column(String(10), nullable=False)  # A, B, C evidence quality
    last_updated = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    
    # Database indexes for fast lookup
    __table_args__ = (
        Index('idx_nice_symptoms', 'primary_symptoms'),
        Index('idx_nice_condition', 'condition_name'),
    )

"""
nice_fhir_seed.py
-----------------
Seed data for 50 NICE-aligned emergency protocols, grouped into 5 categories
(10 per category) with basic FHIR Condition codes.
Each dictionary is kept on a single line so the file stays <200 LOC.
"""

NICE_SEED_DATA = [
 # ---------------------- CARDIOVASCULAR (10) ----------------------
 {"protocol_code" : "CG95_CHEST_PAIN" , "category" : "Cardiovascular" , "condition_name" : "Chest Pain Assessment" , "primary_symptoms" : ["chest_pain" , "chest_discomfort"] , "red_flag_symptoms" : ["radiating_pain" , "sweating" , "dyspnea"] , "initial_questions" : ["Describe the chest pain quality and location." , "Does activity change the pain?" , "Any nausea or sweating?"] , "follow_up_questions" : ["History of heart disease?" , "Risk factors like diabetes or smoking?" , "Relief with nitrates?"] , "emergency_criteria" : "Crushing central pain >20 min with red flags" , "routine_criteria" : "Atypical pain, stable vitals" , "self_care_criteria" : "Musculoskeletal pain reproducible on palpation" , "evidence_level" : "A" , "fhir_code" : "29857009"},
 {"protocol_code" : "NG136_MI" , "category" : "Cardiovascular" , "condition_name" : "Acute Myocardial Infarction" , "primary_symptoms" : ["severe_chest_pain" , "diaphoresis"] , "red_flag_symptoms" : ["hypotension" , "syncope" , "arrhythmia"] , "initial_questions" : ["When did pain start?" , "Any SOB or sweating?" , "Previous MI?"] , "follow_up_questions" : ["Nitroglycerin response?" , "Family cardiac history?" , "Current meds?"] , "emergency_criteria" : "ST-elevation or troponin rise with symptoms" , "routine_criteria" : "Resolved pain, normal biomarkers" , "self_care_criteria" : "None – always clinician review" , "evidence_level" : "A" , "fhir_code" : "22298006"},
 {"protocol_code" : "CG14_UNSTABLE_ANGINA" , "category" : "Cardiovascular" , "condition_name" : "Unstable Angina" , "primary_symptoms" : ["rest_chest_pain"] , "red_flag_symptoms" : ["new_onset_angina" , "increasing_frequency"] , "initial_questions" : ["Is pain occurring at rest?" , "How long does it last?" , "Any radiation?"] , "follow_up_questions" : ["Risk factors?" , "Aspirin taken?" , "Previous stents?"] , "emergency_criteria" : "New rest pain <24 h or crescendo pattern" , "routine_criteria" : "Stable exertional pattern" , "self_care_criteria" : "None – specialist follow-up" , "evidence_level" : "A" , "fhir_code" : "413444003"},
 {"protocol_code" : "PE_EMERGENCY" , "category" : "Cardiovascular" , "condition_name" : "Pulmonary Embolism" , "primary_symptoms" : ["pleuritic_pain" , "sudden_dyspnea"] , "red_flag_symptoms" : ["collapse" , "hypoxia"] , "initial_questions" : ["Onset of breathlessness?" , "Recent travel/surgery?" , "Leg swelling?"] , "follow_up_questions" : ["Cancer history?" , "Hormonal therapy?" , "Prior clots?"] , "emergency_criteria" : "Shock or SpO₂<90 % with suspected PE" , "routine_criteria" : "Low Wells score, stable vitals" , "self_care_criteria" : "None – imaging required" , "evidence_level" : "A" , "fhir_code" : "59282003"},
 {"protocol_code" : "NG17_AORTIC_DISSECTION" , "category" : "Cardiovascular" , "condition_name" : "Aortic Dissection" , "primary_symptoms" : ["tearing_chest_pain" , "back_pain"] , "red_flag_symptoms" : ["pulse_deficit" , "neurological_deficit"] , "initial_questions" : ["Describe pain character." , "Radiation to back?" , "Known aneurysm?"] , "follow_up_questions" : ["Marfan features?" , "Hypertension history?" , "Trauma?"] , "emergency_criteria" : "Sudden tearing pain plus unequal BP" , "routine_criteria" : "Stable chronic dissection on imaging" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "233985008"},
 {"protocol_code" : "NG106_ACUTE_HF" , "category" : "Cardiovascular" , "condition_name" : "Acute Heart Failure" , "primary_symptoms" : ["orthopnea" , "paroxysmal_nocturnal_dyspnea"] , "red_flag_symptoms" : ["pulmonary_edema" , "hypotension"] , "initial_questions" : ["How many pillows at night?" , "Leg swelling?" , "Weight gain?"] , "follow_up_questions" : ["Known EF?" , "Recent MI?" , "Alcohol intake?"] , "emergency_criteria" : "Respiratory distress or SpO₂<90 %" , "routine_criteria" : "Mild edema responsive to diuretics" , "self_care_criteria" : "Lifestyle optimization" , "evidence_level" : "A" , "fhir_code" : "84114007"},
 {"protocol_code" : "CG94_VTACH" , "category" : "Cardiovascular" , "condition_name" : "Ventricular Tachycardia" , "primary_symptoms" : ["palpitations" , "dizziness"] , "red_flag_symptoms" : ["syncope" , "hemodynamic_instability"] , "initial_questions" : ["Palpitations onset?" , "Chest pain?" , "Implanted ICD?"] , "follow_up_questions" : ["Electrolyte issues?" , "Drug triggers?" , "Family SCD?"] , "emergency_criteria" : "Sustained VT with instability" , "routine_criteria" : "Non-sustained, asymptomatic" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "426644000"},
 {"protocol_code" : "NG74_CARDIAC_TAMPONADE" , "category" : "Cardiovascular" , "condition_name" : "Cardiac Tamponade" , "primary_symptoms" : ["progressive_dyspnea" , "chest_pressure"] , "red_flag_symptoms" : ["muffled_heart_sounds" , "pulsus_paradoxus"] , "initial_questions" : ["Recent pericarditis?" , "Trauma history?" , "Cancer?"] , "follow_up_questions" : ["Anticoagulation use?" , "Autoimmune disease?" , "Dialysis?"] , "emergency_criteria" : "Beck's triad with shock" , "routine_criteria" : "Small pericardial effusion, stable" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "422623009"},
 {"protocol_code" : "NG136_HTN_CRISIS" , "category" : "Cardiovascular" , "condition_name" : "Hypertensive Emergency" , "primary_symptoms" : ["severe_headache" , "visual_disturbance"] , "red_flag_symptoms" : ["BP>180/120" , "end_organ_damage"] , "initial_questions" : ["Known HTN?" , "Medication adherence?" , "Neurological symptoms?"] , "follow_up_questions" : ["Chest pain?" , "Kidney disease?" , "Pregnancy?"] , "emergency_criteria" : "Acute target-organ damage with BP crisis" , "routine_criteria" : "Asymptomatic severe HTN" , "self_care_criteria" : "Lifestyle measures for stage-1 HTN" , "evidence_level" : "A" , "fhir_code" : "5204005"},
 {"protocol_code" : "NG87_CARDIOGENIC_SHOCK" , "category" : "Cardiovascular" , "condition_name" : "Cardiogenic Shock" , "primary_symptoms" : ["cold_clammy_skin" , "oliguria"] , "red_flag_symptoms" : ["SBP<90" , "altered_mental_status"] , "initial_questions" : ["Chest pain preceding?" , "Fluid intake?" , "Arrhythmias?"] , "follow_up_questions" : ["Echo available?" , "MI care?" , "Renal function?"] , "emergency_criteria" : "Low BP with signs of hypoperfusion" , "routine_criteria" : "Compensated low EF without shock" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "705981003"},

 # ---------------------- RESPIRATORY (10) ----------------------
 {"protocol_code" : "NG80_ASTHMA_EXAC" , "category" : "Respiratory" , "condition_name" : "Acute Severe Asthma" , "primary_symptoms" : ["wheeze" , "dyspnea"] , "red_flag_symptoms" : ["silent_chest" , "exhaustion"] , "initial_questions" : ["Inhaler use today?" , "Peak flow reading?" , "Previous ICU admissions?"] , "follow_up_questions" : ["Trigger exposure?" , "Steroid use?" , "Allergies?"] , "emergency_criteria" : "PEF<50 % or SpO₂<92 %" , "routine_criteria" : "Mild attack responsive to bronchodilator" , "self_care_criteria" : "Controlled asthma with action plan" , "evidence_level" : "A" , "fhir_code" : "195967001"},
 {"protocol_code" : "COPD_EXAC" , "category" : "Respiratory" , "condition_name" : "COPD Exacerbation" , "primary_symptoms" : ["increased_dyspnea" , "productive_cough"] , "red_flag_symptoms" : ["cyanosis" , "confusion"] , "initial_questions" : ["Sputum color change?" , "Home oxygen?" , "Smoking status?"] , "follow_up_questions" : ["Prev hospitalizations?" , "Vaccination status?" , "Steroid courses?"] , "emergency_criteria" : "Severe dyspnea or acidosis" , "routine_criteria" : "Moderate exacerbation, stable sats" , "self_care_criteria" : "Mild increase in symptoms managed at home" , "evidence_level" : "B" , "fhir_code" : "116289008"},
 {"protocol_code" : "PULM_EDEMA" , "category" : "Respiratory" , "condition_name" : "Acute Pulmonary Edema" , "primary_symptoms" : ["pink_frothy_sputum" , "orthopnea"] , "red_flag_symptoms" : ["severe_hypoxia" , "crackles_all_zones"] , "initial_questions" : ["Onset of symptoms?" , "Chest pain?" , "Hypertension history?"] , "follow_up_questions" : ["Medication compliance?" , "Renal issues?" , "Alcohol intake?"] , "emergency_criteria" : "Resp distress with hypoxia despite O₂" , "routine_criteria" : "Mild edema responsive to diuretics" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "59621000"},
 {"protocol_code" : "TENSION_PT" , "category" : "Respiratory" , "condition_name" : "Tension Pneumothorax" , "primary_symptoms" : ["sudden_chest_pain" , "dyspnea"] , "red_flag_symptoms" : ["tracheal_deviation" , "absent_breath_sounds"] , "initial_questions" : ["Trauma?" , "COPD bullae?" , "Procedures?"] , "follow_up_questions" : ["Previous pneumothorax?" , "Smoking?" , "Connective tissue disease?"] , "emergency_criteria" : "Hemodynamic compromise with unilateral hyperresonance" , "routine_criteria" : "Small stable pneumothorax" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "68270000"},
 {"protocol_code" : "HEMOTHORAX" , "category" : "Respiratory" , "condition_name" : "Massive Hemothorax" , "primary_symptoms" : ["chest_fullness" , "dyspnea"] , "red_flag_symptoms" : ["shock" , "dullness_to_percussion"] , "initial_questions" : ["Trauma details?" , "Anticoagulant use?" , "Breathlessness severity?"] , "follow_up_questions" : ["Allergies?" , "Prior thoracic surgery?" , "Blood type known?"] , "emergency_criteria" : ">1.5 L blood loss or shock" , "routine_criteria" : "Small, non-progressive collection" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "422400008"},
 {"protocol_code" : "SEV_PNEUMONIA" , "category" : "Respiratory" , "condition_name" : "Severe Community-Acquired Pneumonia" , "primary_symptoms" : ["fever" , "productive_cough"] , "red_flag_symptoms" : ["SpO₂<90" , "confusion"] , "initial_questions" : ["Duration of symptoms?" , "Vaccinations?" , "Travel history?"] , "follow_up_questions" : ["Comorbidities?" , "Smoking?" , "Antibiotic allergies?"] , "emergency_criteria" : "CURB-65≥3 or sepsis" , "routine_criteria" : "Mild pneumonia outpatient" , "self_care_criteria" : "Viral URI" , "evidence_level" : "A" , "fhir_code" : "233604007"},
 {"protocol_code" : "FBAO" , "category" : "Respiratory" , "condition_name" : "Foreign Body Airway Obstruction" , "primary_symptoms" : ["sudden_cough" , "inability_to_speak"] , "red_flag_symptoms" : ["cyanosis" , "collapse"] , "initial_questions" : ["What was ingested?" , "Onset time?" , "Attempts to clear?"] , "follow_up_questions" : ["Witnessed choking?" , "Underlying dysphagia?" , "CPR performed?"] , "emergency_criteria" : "Partial or complete obstruction compromising airway" , "routine_criteria" : "Resolved obstruction, no symptoms" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "86049000"},
 {"protocol_code" : "ARDS" , "category" : "Respiratory" , "condition_name" : "Acute Respiratory Distress Syndrome" , "primary_symptoms" : ["severe_dyspnea" , "tachypnea"] , "red_flag_symptoms" : ["refractory_hypoxemia" , "bilateral_infiltrates"] , "initial_questions" : ["Trigger event?" , "Sepsis signs?" , "Smoke inhalation?"] , "follow_up_questions" : ["Fluid balance?" , "Ventilation history?" , "Comorbidities?"] , "emergency_criteria" : "PaO₂/FiO₂<200 with bilateral opacities" , "routine_criteria" : "ALI criteria but stable" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "67782005"},
 {"protocol_code" : "ANAPHYLAXIS_AIRWAY" , "category" : "Respiratory" , "condition_name" : "Anaphylaxis with Airway Compromise" , "primary_symptoms" : ["stridor" , "facial_swelling"] , "red_flag_symptoms" : ["hypotension" , "collapse"] , "initial_questions" : ["Allergen exposure?" , "Epi-pen used?" , "Previous reactions?"] , "follow_up_questions" : ["Asthma history?" , "β-blocker use?" , "Mastocytosis?"] , "emergency_criteria" : "Airway edema or shock" , "routine_criteria" : "Mild urticaria only" , "self_care_criteria" : "Allergen avoidance education" , "evidence_level" : "A" , "fhir_code" : "39579001"},
 {"protocol_code" : "COVID_SEVERE" , "category" : "Respiratory" , "condition_name" : "Severe COVID-19 Pneumonia" , "primary_symptoms" : ["fever" , "cough" , "dyspnea"] , "red_flag_symptoms" : ["SpO₂<92" , "tachypnea>30"] , "initial_questions" : ["Vaccination status?" , "Onset date?" , "Home oximetry readings?"] , "follow_up_questions" : ["Comorbidities?" , "Steroid started?" , "Contact tracing?"] , "emergency_criteria" : "Severe hypoxia or respiratory failure" , "routine_criteria" : "Mild disease managed at home" , "self_care_criteria" : "Isolation and monitoring" , "evidence_level" : "B" , "fhir_code" : "840539006"},

 # ---------------------- NEUROLOGICAL (10) ----------------------
 {"protocol_code" : "NG127_HEADACHE" , "category" : "Neurological" , "condition_name" : "Headache Assessment" , "primary_symptoms" : ["headache" , "photophobia"] , "red_flag_symptoms" : ["thunderclap" , "neck_stiffness"] , "initial_questions" : ["Pain location and quality?" , "Onset time?" , "Associated nausea?"] , "follow_up_questions" : ["Worst ever headache?" , "Neck stiffness?" , "Recent trauma?"] , "emergency_criteria" : "Sudden worst headache, neuro deficit" , "routine_criteria" : "Tension headache pattern" , "self_care_criteria" : "Known migraine responsive to OTC" , "evidence_level" : "A" , "fhir_code" : "25064002"},
 {"protocol_code" : "ISCHEMIC_STROKE" , "category" : "Neurological" , "condition_name" : "Acute Ischemic Stroke" , "primary_symptoms" : ["unilateral_weakness" , "speech_difficulty"] , "red_flag_symptoms" : ["facial_droop" , "gaze_palsy"] , "initial_questions" : ["Last known well?" , "Anticoagulant use?" , "Onset witnessed?"] , "follow_up_questions" : ["Hypertension history?" , "Glucose level?" , "Previous stroke?"] , "emergency_criteria" : "Onset <4.5 h with deficits" , "routine_criteria" : "TIA resolved" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "44054006"},
 {"protocol_code" : "ICH" , "category" : "Neurological" , "condition_name" : "Intracerebral Hemorrhage" , "primary_symptoms" : ["sudden_headache" , "hemiparesis"] , "red_flag_symptoms" : ["vomiting" , "decreased_consciousness"] , "initial_questions" : ["Anticoagulant use?" , "Trauma?" , "Hypertension?"] , "follow_up_questions" : ["Alcohol abuse?" , "Previous ICH?" , "Seizure?"] , "emergency_criteria" : "Acute neuro deficit with high BP" , "routine_criteria" : "Chronic small bleed, stable" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "274100004"},
 {"protocol_code" : "SAH" , "category" : "Neurological" , "condition_name" : "Subarachnoid Hemorrhage" , "primary_symptoms" : ["thunderclap_headache" , "photophobia"] , "red_flag_symptoms" : ["neck_stiffness" , "collapse"] , "initial_questions" : ["Worst headache ever?" , "Syncope?" , "Drug use?"] , "follow_up_questions" : ["Family aneurysm?" , "Hypertension?" , "Vomiting?"] , "emergency_criteria" : "Thunderclap headache ± neuro signs" , "routine_criteria" : "Resolved headache, normal CT" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "233963000"},
 {"protocol_code" : "STATUS_EPI" , "category" : "Neurological" , "condition_name" : "Status Epilepticus" , "primary_symptoms" : ["continuous_seizure" , "unconsciousness"] , "red_flag_symptoms" : ["cyanosis" , "hypoxia"] , "initial_questions" : ["Duration of seizure?" , "Anti-seizure meds adherence?" , "Alcohol withdrawal?"] , "follow_up_questions" : ["Head trauma?" , "Infection?" , "Pregnancy?"] , "emergency_criteria" : ">5 min seizure or recurrent w/o recovery" , "routine_criteria" : "Brief self-limited seizure" , "self_care_criteria" : "Medication compliance counseling" , "evidence_level" : "A" , "fhir_code" : "230711007"},
 {"protocol_code" : "MENINGITIS_ACUTE" , "category" : "Neurological" , "condition_name" : "Acute Bacterial Meningitis" , "primary_symptoms" : ["fever" , "neck_stiffness"] , "red_flag_symptoms" : ["photophobia" , "petichial_rash"] , "initial_questions" : ["Onset of fever?" , "Vaccination status?" , "Seizures?"] , "follow_up_questions" : ["Recent URTI?" , "Immunocompromised?" , "Travel?"] , "emergency_criteria" : "Sepsis signs or neuro deficit" , "routine_criteria" : "Viral meningitis suspicion" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "7180009"},
 {"protocol_code" : "GBS" , "category" : "Neurological" , "condition_name" : "Guillain-Barré Syndrome" , "primary_symptoms" : ["ascending_weakness" , "paresthesia"] , "red_flag_symptoms" : ["respiratory_muscle_weakness" , "autonomic_instability"] , "initial_questions" : ["Onset after infection?" , "Vaccinations?" , "Walking ability?"] , "follow_up_questions" : ["Facial weakness?" , "Bulbar symptoms?" , "Pain?"] , "emergency_criteria" : "Rapid progression <4 h or FVC<20 mL/kg" , "routine_criteria" : "Slow progression, ambulatory" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "40956001"},
 {"protocol_code" : "TBI_SEVERE" , "category" : "Neurological" , "condition_name" : "Severe Traumatic Brain Injury" , "primary_symptoms" : ["loss_of_consciousness" , "vomiting"] , "red_flag_symptoms" : ["GCS<8" , "pupil_asymmetry"] , "initial_questions" : ["Mechanism of injury?" , "Helmet worn?" , "Seizure?"] , "follow_up_questions" : ["Anticoagulant?" , "Alcohol?" , "Previous TBI?"] , "emergency_criteria" : "GCS<9 or neuro deficit" , "routine_criteria" : "Mild concussion" , "self_care_criteria" : "Return-to-play advice" , "evidence_level" : "A" , "fhir_code" : "86299005"},
 {"protocol_code" : "SPINAL_COMP" , "category" : "Neurological" , "condition_name" : "Spinal Cord Compression" , "primary_symptoms" : ["back_pain" , "weakness"] , "red_flag_symptoms" : ["bladder_retention" , "saddle_anesthesia"] , "initial_questions" : ["Cancer history?" , "Trauma?" , "Onset speed?"] , "follow_up_questions" : ["Steroid use?" , "Chemotherapy?" , "Radiation?"] , "emergency_criteria" : "Neurological deficit with compression signs" , "routine_criteria" : "Chronic pain without deficit" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "74306000"},
 {"protocol_code" : "MYASTHENIC_CRISIS" , "category" : "Neurological" , "condition_name" : "Myasthenic Crisis" , "primary_symptoms" : ["respiratory_weakness" , "ptosis"] , "red_flag_symptoms" : ["hypercapnia" , "bulbar_dysfunction"] , "initial_questions" : ["Medication compliance?" , "Infection?" , "Recent surgery?"] , "follow_up_questions" : ["Thymectomy?" , "Autoimmune disorders?" , "Drug triggers?"] , "emergency_criteria" : "Need for ventilatory support" , "routine_criteria" : "Mild weakness responsive to meds" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "91936005"},

 # ---------------------- GASTROINTESTINAL (10) ----------------------
 {"protocol_code" : "ACUTE_PANCREATITIS" , "category" : "Gastrointestinal" , "condition_name" : "Acute Pancreatitis" , "primary_symptoms" : ["epigastric_pain" , "vomiting"] , "red_flag_symptoms" : ["hypotension" , "hypocalcemia"] , "initial_questions" : ["Alcohol intake?" , "Gallstones?" , "Pain radiation?"] , "follow_up_questions" : ["Lipase done?" , "Previous attacks?" , "Drug triggers?"] , "emergency_criteria" : "Severe pancreatitis with organ failure" , "routine_criteria" : "Mild pancreatitis, tolerating oral" , "self_care_criteria" : "Dietary advice post-episode" , "evidence_level" : "A" , "fhir_code" : "235719002"},
 {"protocol_code" : "PERF_ULCER" , "category" : "Gastrointestinal" , "condition_name" : "Perforated Peptic Ulcer" , "primary_symptoms" : ["sudden_epigastric_pain" , "rigid_abdomen"] , "red_flag_symptoms" : ["peritonitis" , "shock"] , "initial_questions" : ["NSAID use?" , "H. pylori?" , "Previous ulcer?"] , "follow_up_questions" : ["Alcohol?" , "Steroids?" , "Anticoagulants?"] , "emergency_criteria" : "Free air under diaphragm + peritonitis" , "routine_criteria" : "Ulcer pain without perforation" , "self_care_criteria" : "PPI therapy lifestyle" , "evidence_level" : "A" , "fhir_code" : "191233003"},
 {"protocol_code" : "VARICEAL_BLEED" , "category" : "Gastrointestinal" , "condition_name" : "Variceal Upper GI Bleed" , "primary_symptoms" : ["hematemesis" , "melena"] , "red_flag_symptoms" : ["hypotension" , "tachycardia"] , "initial_questions" : ["Liver disease history?" , "Alcohol?" , "Volume of blood?"] , "follow_up_questions" : ["Beta-blocker use?" , "Recent endoscopy?" , "Encephalopathy?"] , "emergency_criteria" : "Active bleeding with shock" , "routine_criteria" : "Portal hypertension but no bleed" , "self_care_criteria" : "Abstinence counseling" , "evidence_level" : "A" , "fhir_code" : "87600003"},
 {"protocol_code" : "MESENTERIC_ISCHEMIA" , "category" : "Gastrointestinal" , "condition_name" : "Acute Mesenteric Ischemia" , "primary_symptoms" : ["severe_abdominal_pain" , "out_of_proportion_pain"] , "red_flag_symptoms" : ["bloody_stools" , "peritonitis"] , "initial_questions" : ["AFib history?" , "Weight loss?" , "Pain after eating?"] , "follow_up_questions" : ["Smoking?" , "Vascular disease?" , "D-dimer?"] , "emergency_criteria" : "CT angiography showing occlusion" , "routine_criteria" : "Chronic ischemia, stable" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "71444005"},
 {"protocol_code" : "BOWEL_OBSTRUCTION" , "category" : "Gastrointestinal" , "condition_name" : "Small Bowel Obstruction" , "primary_symptoms" : ["colicky_pain" , "vomiting"] , "red_flag_symptoms" : ["peritonitis" , "strangulation"] , "initial_questions" : ["Previous surgeries?" , "Hernias?" , "Onset of distension?"] , "follow_up_questions" : ["Flatus passed?" , "Fever?" , "CT scan?"] , "emergency_criteria" : "Strangulated obstruction or peritonitis" , "routine_criteria" : "Partial obstruction responsive to NG" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "5602001"},
 {"protocol_code" : "APPENDICITIS_PERF" , "category" : "Gastrointestinal" , "condition_name" : "Perforated Appendicitis" , "primary_symptoms" : ["right_lower_quad_pain" , "fever"] , "red_flag_symptoms" : ["guarding" , "rebound_tenderness"] , "initial_questions" : ["Pain migration?" , "Nausea?" , "Loss of appetite?"] , "follow_up_questions" : ["Pregnancy?" , "Previous episodes?" , "CT findings?"] , "emergency_criteria" : "Peritonitis or abscess" , "routine_criteria" : "Uncomplicated early appendicitis" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "62413002"},
 {"protocol_code" : "CHOLECYSTITIS_SEPSIS" , "category" : "Gastrointestinal" , "condition_name" : "Acute Cholecystitis with Sepsis" , "primary_symptoms" : ["RUQ_pain" , "fever"] , "red_flag_symptoms" : ["jaundice" , "hypotension"] , "initial_questions" : ["Gallstone history?" , "Vomiting?" , "Murphy sign?"] , "follow_up_questions" : ["Antibiotic allergies?" , "Diabetes?" , "Pregnancy?"] , "emergency_criteria" : "Sepsis or gallbladder perforation" , "routine_criteria" : "Biliary colic only" , "self_care_criteria" : "Dietary fat reduction" , "evidence_level" : "A" , "fhir_code" : "235595009"},
 {"protocol_code" : "BOERHAAVE" , "category" : "Gastrointestinal" , "condition_name" : "Esophageal Rupture" , "primary_symptoms" : ["severe_chest_pain" , "subcutaneous_emphysema"] , "red_flag_symptoms" : ["shock" , "hematemesis"] , "initial_questions" : ["Forceful vomiting?" , "Alcohol binge?" , "Swallowing foreign body?"] , "follow_up_questions" : ["Endoscopy?" , "Mediastinitis signs?" , "Pleural effusion?"] , "emergency_criteria" : "CT confirming perforation" , "routine_criteria" : "Mallory-Weiss tear" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "109838007"},
 {"protocol_code" : "ACUTE_LIVER_FAILURE" , "category" : "Gastrointestinal" , "condition_name" : "Acute Liver Failure" , "primary_symptoms" : ["jaundice" , "altered_mental_status"] , "red_flag_symptoms" : ["coagulopathy" , "cerebral_edema"] , "initial_questions" : ["Paracetamol overdose?" , "Viral hepatitis risk?" , "Drug history?"] , "follow_up_questions" : ["INR value?" , "Ammonia level?" , "Renal function?"] , "emergency_criteria" : "INR>1.5 with encephalopathy" , "routine_criteria" : "Compensated cirrhosis" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "197315008"},
 {"protocol_code" : "DIVERTICULAR_PERF" , "category" : "Gastrointestinal" , "condition_name" : "Perforated Diverticulitis" , "primary_symptoms" : ["left_lower_quad_pain" , "fever"] , "red_flag_symptoms" : ["peritonitis" , "abscess"] , "initial_questions" : ["Previous episodes?" , "Bowel habits?" , "Antibiotic use?"] , "follow_up_questions" : ["CT findings?" , "Immunosuppression?" , "Bleeding?"] , "emergency_criteria" : "Free perforation with sepsis" , "routine_criteria" : "Uncomplicated diverticulitis" , "self_care_criteria" : "High-fiber diet advice" , "evidence_level" : "B" , "fhir_code" : "27550009"},

 # ---------------------- TRAUMA (10) ----------------------
 {"protocol_code" : "POLYTRAUMA" , "category" : "Trauma" , "condition_name" : "Polytrauma" , "primary_symptoms" : ["multiple_injuries" , "hypotension"] , "red_flag_symptoms" : ["GCS<8" , "SBP<90"] , "initial_questions" : ["Mechanism of injury?" , "Time since incident?" , "Protective gear?"] , "follow_up_questions" : ["Allergies?" , "Anticoagulants?" , "Last meal?"] , "emergency_criteria" : "ABC compromise or shock" , "routine_criteria" : "Minor injuries only" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "444972004"},
 {"protocol_code" : "PEN_ABD_TRAUMA" , "category" : "Trauma" , "condition_name" : "Penetrating Abdominal Trauma" , "primary_symptoms" : ["abdominal_pain" , "external_bleeding"] , "red_flag_symptoms" : ["evisceration" , "peritonitis"] , "initial_questions" : ["Weapon type?" , "Entry/exit wounds?" , "Pain level?"] , "follow_up_questions" : ["Tetanus status?" , "FAST scan?" , "Hemoglobin?"] , "emergency_criteria" : "Peritonitis or hemodynamic instability" , "routine_criteria" : "Superficial wound only" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "125666000"},
 {"protocol_code" : "PELVIC_FRAC" , "category" : "Trauma" , "condition_name" : "Pelvic Fracture with Hemorrhage" , "primary_symptoms" : ["pelvic_pain" , "inability_to_bear_weight"] , "red_flag_symptoms" : ["hypotension" , "urethral_bleed"] , "initial_questions" : ["High-energy impact?" , "Hematuria?" , "Leg length discrepancy?"] , "follow_up_questions" : ["IV access?" , "Pelvic binder applied?" , "CT angiography?"] , "emergency_criteria" : "Shock or open fracture" , "routine_criteria" : "Stable pubic rami fracture" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "239873007"},
 {"protocol_code" : "OPEN_LONG_BONE" , "category" : "Trauma" , "condition_name" : "Open Long-Bone Fracture" , "primary_symptoms" : ["visible_bone" , "severe_pain"] , "red_flag_symptoms" : ["neurovascular_deficit" , "compartment_syndrome"] , "initial_questions" : ["Mechanism?" , "Contamination?" , "Tetanus status?"] , "follow_up_questions" : ["Analgesia given?" , "Splint applied?" , "Bleeding control?"] , "emergency_criteria" : "Open fracture Gustilo III or NV deficit" , "routine_criteria" : "Closed fracture" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "263195009"},
 {"protocol_code" : "SUS_SPINAL_INJ" , "category" : "Trauma" , "condition_name" : "Suspected Spinal Injury" , "primary_symptoms" : ["neck_pain" , "numbness"] , "red_flag_symptoms" : ["paralysis" , "priapism"] , "initial_questions" : ["High-risk mechanism?" , "Pain location?" , "Weakness?"] , "follow_up_questions" : ["Immobilization done?" , "Sensory exam?" , "Rectal tone?"] , "emergency_criteria" : "Neuro deficit or unstable fracture" , "routine_criteria" : "Whiplash without neuro signs" , "self_care_criteria" : "Posture education" , "evidence_level" : "A" , "fhir_code" : "125605004"},
 {"protocol_code" : "CRUSH_RHABDO" , "category" : "Trauma" , "condition_name" : "Crush Injury with Rhabdomyolysis" , "primary_symptoms" : ["limb_swelling" , "pain"] , "red_flag_symptoms" : ["dark_urine" , "hyperkalemia"] , "initial_questions" : ["Duration of entrapment?" , "Urine color?" , "Pain severity?"] , "follow_up_questions" : ["CK level?" , "Renal function?" , "Fluid resuscitation?"] , "emergency_criteria" : "Hyperkalemia or CK>5000" , "routine_criteria" : "Minor soft-tissue injury" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "225566009"},
 {"protocol_code" : "SEV_BURN" , "category" : "Trauma" , "condition_name" : "Severe Burn >30 % TBSA" , "primary_symptoms" : ["pain" , "blistering"] , "red_flag_symptoms" : ["inhalation_injury" , "hypovolemia"] , "initial_questions" : ["Cause of burn?" , "TBSA estimate?" , "Enclosed space?"] , "follow_up_questions" : ["Tetanus?" , "Fluid formula?" , "Analgesia?"] , "emergency_criteria" : ">30 % TBSA or circumferential burns" , "routine_criteria" : "Minor partial-thickness burn" , "self_care_criteria" : "Topical care for <5 % burn" , "evidence_level" : "A" , "fhir_code" : "49550006"},
 {"protocol_code" : "TRAUM_AMP" , "category" : "Trauma" , "condition_name" : "Traumatic Amputation" , "primary_symptoms" : ["limb_loss" , "hemorrhage"] , "red_flag_symptoms" : ["hypotension" , "shock"] , "initial_questions" : ["Time of amputation?" , "Part preserved?" , "Mechanism?"] , "follow_up_questions" : ["Tourniquet applied?" , "IV fluids?" , "Tetanus?"] , "emergency_criteria" : "Major limb loss with bleeding" , "routine_criteria" : "Distal fingertip only" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "702958008"},
 {"protocol_code" : "COMP_SYNDROME" , "category" : "Trauma" , "condition_name" : "Acute Compartment Syndrome" , "primary_symptoms" : ["severe_pain_out_of_proportion" , "paresthesia"] , "red_flag_symptoms" : ["pulselessness" , "paralysis"] , "initial_questions" : ["Pain with passive stretch?" , "Mechanism?" , "Analgesia response?"] , "follow_up_questions" : ["Pressure measurement?" , "Anticoagulants?" , "Swelling onset?"] , "emergency_criteria" : "Compartment pressure >30 mmHg" , "routine_criteria" : "Bruising without tight compartment" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "70211007"},
 {"protocol_code" : "TRAUMATIC_PT" , "category" : "Trauma" , "condition_name" : "Traumatic Pneumothorax" , "primary_symptoms" : ["chest_pain" , "dyspnea"] , "red_flag_symptoms" : ["hypotension" , "respiratory_distress"] , "initial_questions" : ["Blunt vs penetrating?" , "Dyspnea severity?" , "LOC?"] , "follow_up_questions" : ["FAST exam?" , "Chest wall deformity?" , "Analgesia?"] , "emergency_criteria" : "Large pneumothorax with distress" , "routine_criteria" : "Small asymptomatic PTX" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "233978006"},

 # ---------------------- INFECTIOUS DISEASE (10) ----------------------
 {"protocol_code" : "NG51_SEPSIS" , "category" : "Infectious Disease" , "condition_name" : "Sepsis and Septic Shock" , "primary_symptoms" : ["fever" , "altered_mental_state"] , "red_flag_symptoms" : ["hypotension" , "lactate>2"] , "initial_questions" : ["Source of infection?" , "Duration of symptoms?" , "Immunocompromised?"] , "follow_up_questions" : ["Recent surgery?" , "Catheter in situ?" , "Antibiotic allergies?"] , "emergency_criteria" : "qSOFA≥2 or lactate>4" , "routine_criteria" : "SIRS without organ dysfunction" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "91302008"},
 {"protocol_code" : "NECROTIZING_FASC" , "category" : "Infectious Disease" , "condition_name" : "Necrotizing Fasciitis" , "primary_symptoms" : ["severe_pain" , "skin_erythema"] , "red_flag_symptoms" : ["skin_necrosis" , "systemic_toxicity"] , "initial_questions" : ["Trauma history?" , "Diabetes?" , "Pain out of proportion?"] , "follow_up_questions" : ["Drug use?" , "Immunosuppression?" , "Rapid progression?"] , "emergency_criteria" : "LRINEC score>6 or systemic toxicity" , "routine_criteria" : "Cellulitis without deep involvement" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "49832006"},
 {"protocol_code" : "ENDOCARDITIS" , "category" : "Infectious Disease" , "condition_name" : "Infective Endocarditis" , "primary_symptoms" : ["fever" , "heart_murmur"] , "red_flag_symptoms" : ["embolic_phenomena" , "heart_failure"] , "initial_questions" : ["IVDU history?" , "Prosthetic valve?" , "Recent dental work?"] , "follow_up_questions" : ["Blood cultures taken?" , "Echo findings?" , "Splinter hemorrhages?"] , "emergency_criteria" : "Acute valve regurgitation or emboli" , "routine_criteria" : "Possible endocarditis, stable" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "56819008"},
 {"protocol_code" : "MALARIA_SEVERE" , "category" : "Infectious Disease" , "condition_name" : "Severe Malaria" , "primary_symptoms" : ["fever" , "rigors"] , "red_flag_symptoms" : ["altered_consciousness" , "severe_anemia"] , "initial_questions" : ["Travel history?" , "Prophylaxis taken?" , "Species identified?"] , "follow_up_questions" : ["Parasitemia level?" , "Renal function?" , "Platelet count?"] , "emergency_criteria" : "Cerebral malaria or >5% parasitemia" , "routine_criteria" : "Uncomplicated P.vivax/ovale" , "self_care_criteria" : "Prevention advice for travel" , "evidence_level" : "A" , "fhir_code" : "61462000"},
 {"protocol_code" : "C_DIFF_SEVERE" , "category" : "Infectious Disease" , "condition_name" : "Severe C. difficile Colitis" , "primary_symptoms" : ["diarrhea" , "abdominal_pain"] , "red_flag_symptoms" : ["toxic_megacolon" , "perforation"] , "initial_questions" : ["Recent antibiotics?" , "Hospital admission?" , "Stool frequency?"] , "follow_up_questions" : ["WCC count?" , "Creatinine rise?" , "Albumin level?"] , "emergency_criteria" : "Toxic megacolon or perforation" , "routine_criteria" : "Mild CDI responsive to metronidazole" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "5933001"},
 {"protocol_code" : "TB_MILIARY" , "category" : "Infectious Disease" , "condition_name" : "Miliary Tuberculosis" , "primary_symptoms" : ["fever" , "night_sweats"] , "red_flag_symptoms" : ["respiratory_failure" , "meningitis"] , "initial_questions" : ["TB contact?" , "HIV status?" , "Country of birth?"] , "follow_up_questions" : ["Weight loss?" , "Sputum AFB?" , "CXR findings?"] , "emergency_criteria" : "Respiratory failure or CNS involvement" , "routine_criteria" : "Pulmonary TB, stable" , "self_care_criteria" : "Contact screening and DOT" , "evidence_level" : "A" , "fhir_code" : "240142002"},
 {"protocol_code" : "NEUTROPENIC_SEPSIS" , "category" : "Infectious Disease" , "condition_name" : "Neutropenic Sepsis" , "primary_symptoms" : ["fever" , "neutrophils<0.5"] , "red_flag_symptoms" : ["hypotension" , "organ_dysfunction"] , "initial_questions" : ["Chemotherapy timing?" , "Central line?" , "Source identified?"] , "follow_up_questions" : ["Prophylactic antibiotics?" , "GCSF used?" , "Mucositis present?"] , "emergency_criteria" : "Shock or MASCC score<21" , "routine_criteria" : "Low-risk neutropenia, stable" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "780857009"},
 {"protocol_code" : "ENCEPHALITIS" , "category" : "Infectious Disease" , "condition_name" : "Viral Encephalitis" , "primary_symptoms" : ["altered_mental_status" , "fever"] , "red_flag_symptoms" : ["seizures" , "focal_neurology"] , "initial_questions" : ["Travel history?" , "Animal contact?" , "Prodromal illness?"] , "follow_up_questions" : ["CSF findings?" , "HSV PCR done?" , "Aciclovir started?"] , "emergency_criteria" : "Rapid deterioration or raised ICP" , "routine_criteria" : "Viral meningitis without encephalitis" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "45170000"},
 {"protocol_code" : "DENGUE_SEVERE" , "category" : "Infectious Disease" , "condition_name" : "Severe Dengue" , "primary_symptoms" : ["fever" , "thrombocytopenia"] , "red_flag_symptoms" : ["plasma_leakage" , "bleeding"] , "initial_questions" : ["Endemic area travel?" , "Day of illness?" , "Previous dengue?"] , "follow_up_questions" : ["Hematocrit rise?" , "Platelet trend?" , "Fluid balance?"] , "emergency_criteria" : "Dengue shock syndrome or severe bleeding" , "routine_criteria" : "Dengue fever without complications" , "self_care_criteria" : "Vector control education" , "evidence_level" : "A" , "fhir_code" : "38362002"},
 {"protocol_code" : "PCP_PNEUMONIA" , "category" : "Infectious Disease" , "condition_name" : "Pneumocystis Pneumonia" , "primary_symptoms" : ["dyspnea_on_exertion" , "dry_cough"] , "red_flag_symptoms" : ["severe_hypoxia" , "pneumothorax"] , "initial_questions" : ["HIV status?" , "CD4 count?" , "Prophylaxis compliance?"] , "follow_up_questions" : ["Exercise desaturation?" , "LDH level?" , "Steroid indicated?"] , "emergency_criteria" : "PaO₂<70 mmHg or pneumothorax" , "routine_criteria" : "Mild PCP, stable oxygen" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "186768009"},

 # ---------------------- ENDOCRINE (10) ----------------------
 {"protocol_code" : "NG15_DKA" , "category" : "Endocrine" , "condition_name" : "Diabetic Ketoacidosis" , "primary_symptoms" : ["polyuria" , "polydipsia"] , "red_flag_symptoms" : ["ketones>3" , "pH<7.3"] , "initial_questions" : ["Known diabetes?" , "Infection trigger?" , "Medication compliance?"] , "follow_up_questions" : ["Abdominal pain?" , "Vomiting?" , "Mental state?"] , "emergency_criteria" : "pH<7.1 or altered consciousness" , "routine_criteria" : "Mild hyperglycemia, no ketosis" , "self_care_criteria" : "Diabetes education and sick day rules" , "evidence_level" : "A" , "fhir_code" : "420422005"},
 {"protocol_code" : "HYPEROSMOLAR_COMA" , "category" : "Endocrine" , "condition_name" : "Hyperosmolar Hyperglycemic State" , "primary_symptoms" : ["altered_mental_status" , "severe_dehydration"] , "red_flag_symptoms" : ["glucose>30" , "osmolality>320"] , "initial_questions" : ["Infection present?" , "Medication changes?" , "Fluid intake?"] , "follow_up_questions" : ["Renal function?" , "Sodium level?" , "Neurological deficit?"] , "emergency_criteria" : "Coma or severe dehydration" , "routine_criteria" : "Hyperglycemia without HHS" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "237633009"},
 {"protocol_code" : "SEVERE_HYPOGLYCEMIA" , "category" : "Endocrine" , "condition_name" : "Severe Hypoglycemia" , "primary_symptoms" : ["confusion" , "sweating"] , "red_flag_symptoms" : ["seizures" , "coma"] , "initial_questions" : ["Diabetes medications?" , "Last meal?" , "Alcohol intake?"] , "follow_up_questions" : ["Recurrent episodes?" , "Glucagon available?" , "Driving license?"] , "emergency_criteria" : "Glucose<3 with altered consciousness" , "routine_criteria" : "Mild hypoglycemia, responsive" , "self_care_criteria" : "Hypoglycemia awareness education" , "evidence_level" : "A" , "fhir_code" : "302866003"},
 {"protocol_code" : "ADDISONIAN_CRISIS" , "category" : "Endocrine" , "condition_name" : "Addisonian Crisis" , "primary_symptoms" : ["hypotension" , "hyponatremia"] , "red_flag_symptoms" : ["shock" , "hyperkalemia"] , "initial_questions" : ["Known Addison's?" , "Steroid compliance?" , "Stress/illness?"] , "follow_up_questions" : ["Pigmentation?" , "Weight loss?" , "Cortisol level?"] , "emergency_criteria" : "Shock with electrolyte abnormalities" , "routine_criteria" : "Stable adrenal insufficiency" , "self_care_criteria" : "Steroid sick day rules education" , "evidence_level" : "A" , "fhir_code" : "111556008"},
 {"protocol_code" : "THYROID_STORM" , "category" : "Endocrine" , "condition_name" : "Thyroid Storm" , "primary_symptoms" : ["hyperthermia" , "tachycardia"] , "red_flag_symptoms" : ["heart_failure" , "altered_mental_status"] , "initial_questions" : ["Known hyperthyroidism?" , "Recent iodine?" , "Surgery trigger?"] , "follow_up_questions" : ["Antithyroid meds?" , "Beta-blocker contraindicated?" , "Precipitating factor?"] , "emergency_criteria" : "Burch-Wartofsky score>45" , "routine_criteria" : "Uncomplicated hyperthyroidism" , "self_care_criteria" : "Medication compliance counseling" , "evidence_level" : "B" , "fhir_code" : "306720005"},
 {"protocol_code" : "MYXEDEMA_COMA" , "category" : "Endocrine" , "condition_name" : "Myxedema Coma" , "primary_symptoms" : ["hypothermia" , "altered_mental_status"] , "red_flag_symptoms" : ["hypoventilation" , "bradycardia"] , "initial_questions" : ["Known hypothyroidism?" , "Medication compliance?" , "Precipitating illness?"] , "follow_up_questions" : ["TSH level?" , "Cortisol needed?" , "Warming methods?"] , "emergency_criteria" : "Coma with severe hypothyroidism" , "routine_criteria" : "Asymptomatic hypothyroidism" , "self_care_criteria" : "Thyroxine adherence counseling" , "evidence_level" : "B" , "fhir_code" : "1761006"},
 {"protocol_code" : "PHEOCHROMOCYTOMA_CRISIS" , "category" : "Endocrine" , "condition_name" : "Pheochromocytoma Crisis" , "primary_symptoms" : ["severe_hypertension" , "palpitations"] , "red_flag_symptoms" : ["hypertensive_encephalopathy" , "MI"] , "initial_questions" : ["Paroxysmal symptoms?" , "Family history?" , "Surgery planned?"] , "follow_up_questions" : ["Beta-blocker given first?" , "Catecholamine levels?" , "Imaging findings?"] , "emergency_criteria" : "Hypertensive emergency with catecholamine excess" , "routine_criteria" : "Controlled hypertension" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "302835001"},
 {"protocol_code" : "HYPERCALCEMIC_CRISIS" , "category" : "Endocrine" , "condition_name" : "Hypercalcemic Crisis" , "primary_symptoms" : ["confusion" , "polyuria"] , "red_flag_symptoms" : ["Ca>3.5" , "arrhythmias"] , "initial_questions" : ["Cancer history?" , "Vitamin D supplements?" , "Kidney stones?"] , "follow_up_questions" : ["PTH level?" , "Bisphosphonate contraindicated?" , "ECG changes?"] , "emergency_criteria" : "Ca>3.5 mmol/L or cardiac arrhythmias" , "routine_criteria" : "Mild hypercalcemia, asymptomatic" , "self_care_criteria" : "Dietary calcium counseling" , "evidence_level" : "A" , "fhir_code" : "66931009"},
 {"protocol_code" : "SIADH_SEVERE" , "category" : "Endocrine" , "condition_name" : "Severe SIADH" , "primary_symptoms" : ["hyponatremia" , "confusion"] , "red_flag_symptoms" : ["Na<115" , "seizures"] , "initial_questions" : ["Medications review?" , "Cancer history?" , "Fluid intake?"] , "follow_up_questions" : ["Lung pathology?" , "Urine osmolality?" , "Rate of Na fall?"] , "emergency_criteria" : "Na<115 mmol/L or seizures" , "routine_criteria" : "Mild hyponatremia, asymptomatic" , "self_care_criteria" : "Fluid restriction education" , "evidence_level" : "A" , "fhir_code" : "267198000"},
 {"protocol_code" : "DIABETES_INSIPIDUS" , "category" : "Endocrine" , "condition_name" : "Diabetes Insipidus" , "primary_symptoms" : ["polyuria" , "polydipsia"] , "red_flag_symptoms" : ["hypernatremia" , "dehydration"] , "initial_questions" : ["Head trauma?" , "Neurosurgery?" , "Urine volumes?"] , "follow_up_questions" : ["DDAVP response?" , "Osmolality gradient?" , "MRI findings?"] , "emergency_criteria" : "Severe dehydration or Na>155" , "routine_criteria" : "Controlled with DDAVP" , "self_care_criteria" : "Adequate fluid intake education" , "evidence_level" : "B" , "fhir_code" : "19251005"},

# ---------------------- RENAL/UROLOGICAL (10) ----------------------
 {"protocol_code" : "ACUTE_KIDNEY_INJURY" , "category" : "Renal/Urological" , "condition_name" : "Acute Kidney Injury" , "primary_symptoms" : ["oliguria" , "fluid_retention"] , "red_flag_symptoms" : ["anuria" , "pulmonary_edema"] , "initial_questions" : ["Baseline creatinine?" , "Medication history?" , "Recent contrast?"] , "follow_up_questions" : ["Nephrotoxic drugs?" , "Obstruction signs?" , "Fluid balance?"] , "emergency_criteria" : "Creatinine rise >50% or anuria >12h" , "routine_criteria" : "Stage 1 AKI, stable" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "14669001"},
 {"protocol_code" : "HYPERKALEMIA_SEVERE" , "category" : "Renal/Urological" , "condition_name" : "Severe Hyperkalemia" , "primary_symptoms" : ["muscle_weakness" , "fatigue"] , "red_flag_symptoms" : ["K>6.5" , "ECG_changes"] , "initial_questions" : ["Known CKD?" , "ACE inhibitor use?" , "Dietary intake?"] , "follow_up_questions" : ["ECG performed?" , "Insulin/glucose ready?" , "Dialysis access?"] , "emergency_criteria" : "K>6.5 mmol/L or ECG changes" , "routine_criteria" : "Mild hyperkalemia K 5.1-5.9" , "self_care_criteria" : "Dietary potassium restriction" , "evidence_level" : "A" , "fhir_code" : "237837003"},
 {"protocol_code" : "RENAL_COLIC_OBSTRUCT" , "category" : "Renal/Urological" , "condition_name" : "Obstructing Renal Colic" , "primary_symptoms" : ["severe_flank_pain" , "hematuria"] , "red_flag_symptoms" : ["fever" , "anuria"] , "initial_questions" : ["Pain radiation?" , "Previous stones?" , "Fever present?"] , "follow_up_questions" : ["Stone size on CT?" , "Hydronephrosis?" , "WCC elevated?"] , "emergency_criteria" : "Obstruction with infection or anuria" , "routine_criteria" : "Small stone <5mm, no obstruction" , "self_care_criteria" : "Increased fluid intake, strain urine" , "evidence_level" : "A" , "fhir_code" : "95570007"},
 {"protocol_code" : "BLADDER_RUPTURE" , "category" : "Renal/Urological" , "condition_name" : "Traumatic Bladder Rupture" , "primary_symptoms" : ["inability_to_void" , "pelvic_pain"] , "red_flag_symptoms" : ["gross_hematuria" , "peritonitis"] , "initial_questions" : ["Pelvic trauma?" , "Catheter attempted?" , "Blood at meatus?"] , "follow_up_questions" : ["Cystography findings?" , "Associated injuries?" , "Tetanus status?"] , "emergency_criteria" : "Intraperitoneal rupture or extravasation" , "routine_criteria" : "Minor bladder contusion" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "62167007"},
 {"protocol_code" : "PRIAPISM_ISCHEMIC" , "category" : "Renal/Urological" , "condition_name" : "Ischemic Priapism" , "primary_symptoms" : ["painful_prolonged_erection" , "penile_rigidity"] , "red_flag_symptoms" : ["duration>4h" , "penile_necrosis"] , "initial_questions" : ["Duration of erection?" , "Sickle cell disease?" , "Medications?"] , "follow_up_questions" : ["Previous episodes?" , "Blood gas from penis?" , "Aspiration attempted?"] , "emergency_criteria" : "Ischemic priapism >4h duration" , "routine_criteria" : "High-flow priapism" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "82166005"},
 {"protocol_code" : "TESTICULAR_TORSION" , "category" : "Renal/Urological" , "condition_name" : "Testicular Torsion" , "primary_symptoms" : ["acute_scrotal_pain" , "testicular_swelling"] , "red_flag_symptoms" : ["absent_cremasteric_reflex" , "horizontal_lie"] , "initial_questions" : ["Onset of pain?" , "Previous episodes?" , "Nausea/vomiting?"] , "follow_up_questions" : ["Manual detorsion attempted?" , "Doppler flow?" , "Bilateral fixation needed?"] , "emergency_criteria" : "Clinical torsion <6h onset" , "routine_criteria" : "Epididymitis" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "204878001"},
 {"protocol_code" : "ACUTE_RETENTION" , "category" : "Renal/Urological" , "condition_name" : "Acute Urinary Retention" , "primary_symptoms" : ["inability_to_void" , "suprapubic_pain"] , "red_flag_symptoms" : ["palpable_bladder" , "overflow_incontinence"] , "initial_questions" : ["Last void?" , "Prostate history?" , "Medications?"] , "follow_up_questions" : ["Catheter inserted?" , "Residual volume?" , "Post-void trial?"] , "emergency_criteria" : "Complete retention with pain" , "routine_criteria" : "Chronic retention, asymptomatic" , "self_care_criteria" : "Alpha-blocker therapy" , "evidence_level" : "A" , "fhir_code" : "130949008"},
 {"protocol_code" : "HEMOLYTIC_UREMIC" , "category" : "Renal/Urological" , "condition_name" : "Hemolytic Uremic Syndrome" , "primary_symptoms" : ["bloody_diarrhea" , "pallor"] , "red_flag_symptoms" : ["thrombocytopenia" , "hemolysis"] , "initial_questions" : ["Recent diarrheal illness?" , "E.coli exposure?" , "Urine output?"] , "follow_up_questions" : ["Platelet count?" , "LDH level?" , "Neurological signs?"] , "emergency_criteria" : "Triad with acute renal failure" , "routine_criteria" : "Isolated thrombocytopenia" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "51868009"},
 {"protocol_code" : "RHABDOMYOLYSIS_RENAL" , "category" : "Renal/Urological" , "condition_name" : "Rhabdomyolysis with AKI" , "primary_symptoms" : ["muscle_pain" , "dark_urine"] , "red_flag_symptoms" : ["CK>5000" , "hyperkalemia"] , "initial_questions" : ["Exercise history?" , "Drug use?" , "Trauma?"] , "follow_up_questions" : ["Compartment syndrome?" , "Fluid resuscitation?" , "Urine alkalinization?"] , "emergency_criteria" : "CK>5000 with rising creatinine" , "routine_criteria" : "Mild elevation CK<1000" , "self_care_criteria" : "Exercise modification" , "evidence_level" : "B" , "fhir_code" : "240131006"},
 {"protocol_code" : "CONTRAST_NEPHROPATHY" , "category" : "Renal/Urological" , "condition_name" : "Contrast-Induced Nephropathy" , "primary_symptoms" : ["oliguria" , "fluid_retention"] , "red_flag_symptoms" : ["creatinine_rise>25%" , "metabolic_acidosis"] , "initial_questions" : ["Recent contrast procedure?" , "Pre-hydration given?" , "Baseline GFR?"] , "follow_up_questions" : ["Metformin stopped?" , "NAC given?" , "Diuretic response?"] , "emergency_criteria" : "AKI requiring RRT" , "routine_criteria" : "Transient creatinine rise" , "self_care_criteria" : "Adequate hydration" , "evidence_level" : "A" , "fhir_code" : "236425005"},

 # ---------------------- HEMATOLOGICAL (10) ----------------------
 {"protocol_code" : "ACUTE_LEUKEMIA" , "category" : "Hematological" , "condition_name" : "Acute Leukemia with Leukostasis" , "primary_symptoms" : ["fatigue" , "bleeding"] , "red_flag_symptoms" : ["WCC>100k" , "respiratory_distress"] , "initial_questions" : ["Recent infection?" , "Easy bruising?" , "Blast cells seen?"] , "follow_up_questions" : ["CNS symptoms?" , "Tumor lysis risk?" , "Coagulopathy present?"] , "emergency_criteria" : "WCC>100k with symptoms or blast crisis" , "routine_criteria" : "Chronic leukemia, stable" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "91857003"},
 {"protocol_code" : "TTP_HUS" , "category" : "Hematological" , "condition_name" : "Thrombotic Thrombocytopenic Purpura" , "primary_symptoms" : ["thrombocytopenia" , "microangiopathic_hemolysis"] , "red_flag_symptoms" : ["neurological_deficit" , "fever"] , "initial_questions" : ["Recent illness?" , "Drug history?" , "Neurological symptoms?"] , "follow_up_questions" : ["ADAMTS13 activity?" , "Plasmapheresis available?" , "Platelet transfusion given?"] , "emergency_criteria" : "Classic pentad or neurological involvement" , "routine_criteria" : "ITP without hemolysis" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "66716009"},
 {"protocol_code" : "DIC_ACUTE" , "category" : "Hematological" , "condition_name" : "Disseminated Intravascular Coagulation" , "primary_symptoms" : ["bleeding" , "bruising"] , "red_flag_symptoms" : ["hypofibrinogenemia" , "elevated_D_dimer"] , "initial_questions" : ["Underlying trigger?" , "Sepsis present?" , "Bleeding sites?"] , "follow_up_questions" : ["Platelet count?" , "Fibrinogen level?" , "PT/APTT?"] , "emergency_criteria" : "Active bleeding with coagulopathy" , "routine_criteria" : "Chronic compensated DIC" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "67406007"},
 {"protocol_code" : "HEMOPHILIA_BLEED" , "category" : "Hematological" , "condition_name" : "Major Hemophilia Bleed" , "primary_symptoms" : ["prolonged_bleeding" , "joint_swelling"] , "red_flag_symptoms" : ["CNS_bleed" , "retroperitoneal_hematoma"] , "initial_questions" : ["Factor level known?" , "Recent trauma?" , "Inhibitor present?"] , "follow_up_questions" : ["Factor concentrate available?" , "Desmopressin indicated?" , "Antifibrinolytic use?"] , "emergency_criteria" : "CNS or life-threatening hemorrhage" , "routine_criteria" : "Minor soft tissue bleeding" , "self_care_criteria" : "RICE therapy for joints" , "evidence_level" : "A" , "fhir_code" : "90935002"},
 {"protocol_code" : "SICKLE_CRISIS" , "category" : "Hematological" , "condition_name" : "Sickle Cell Vaso-occlusive Crisis" , "primary_symptoms" : ["severe_pain" , "swelling"] , "red_flag_symptoms" : ["acute_chest_syndrome" , "stroke"] , "initial_questions" : ["Pain location?" , "Triggers?" , "Oxygen saturation?"] , "follow_up_questions" : ["Exchange transfusion needed?" , "Infection ruled out?" , "Adequate hydration?"] , "emergency_criteria" : "Acute chest syndrome or CNS involvement" , "routine_criteria" : "Mild pain crisis" , "self_care_criteria" : "Hydration, avoid triggers" , "evidence_level" : "A" , "fhir_code" : "417357006"},
 {"protocol_code" : "APLASTIC_CRISIS" , "category" : "Hematological" , "condition_name" : "Aplastic Crisis" , "primary_symptoms" : ["pancytopenia" , "fatigue"] , "red_flag_symptoms" : ["severe_anemia" , "bleeding"] , "initial_questions" : ["Recent infection?" , "Parvovirus B19?" , "Blood transfusion history?"] , "follow_up_questions" : ["Bone marrow biopsy?" , "HLA typing?" , "Immunosuppressive therapy?"] , "emergency_criteria" : "Severe pancytopenia with bleeding/infection" , "routine_criteria" : "Moderate aplastic anemia" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "306058006"},
 {"protocol_code" : "MASSIVE_TRANSFUSION" , "category" : "Hematological" , "condition_name" : "Massive Transfusion Protocol" , "primary_symptoms" : ["hemorrhagic_shock" , "coagulopathy"] , "red_flag_symptoms" : [">10_units_RBC" , "acidosis"] , "initial_questions" : ["Blood loss estimate?" , "Trauma mechanism?" , "Coagulation status?"] , "follow_up_questions" : ["Thromboelastography?" , "Fibrinogen level?" , "Hypothermia present?"] , "emergency_criteria" : "Exsanguinating hemorrhage" , "routine_criteria" : "Controlled bleeding <4 units" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "71181003"},
 {"protocol_code" : "TUMOR_LYSIS" , "category" : "Hematological" , "condition_name" : "Tumor Lysis Syndrome" , "primary_symptoms" : ["hyperuricemia" , "hyperkalemia"] , "red_flag_symptoms" : ["acute_renal_failure" , "cardiac_arrhythmia"] , "initial_questions" : ["Chemotherapy started?" , "High tumor burden?" , "Adequate hydration?"] , "follow_up_questions" : ["Allopurinol given?" , "Rasburicase needed?" , "Electrolyte monitoring?"] , "emergency_criteria" : "Laboratory TLS with organ dysfunction" , "routine_criteria" : "High-risk patient, preventive measures" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "423666007"},
 {"protocol_code" : "HYPERVISCOSITY" , "category" : "Hematological" , "condition_name" : "Hyperviscosity Syndrome" , "primary_symptoms" : ["visual_disturbance" , "altered_mental_status"] , "red_flag_symptoms" : ["retinal_hemorrhage" , "heart_failure"] , "initial_questions" : ["Paraprotein level?" , "Visual symptoms?" , "Bleeding history?"] , "follow_up_questions" : ["Plasmapheresis available?" , "Underlying malignancy?" , "Viscosity measured?"] , "emergency_criteria" : "Symptomatic hyperviscosity" , "routine_criteria" : "Asymptomatic paraproteinemia" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "234467004"},
 {"protocol_code" : "FEBRILE_NEUTROPENIA" , "category" : "Hematological" , "condition_name" : "High-Risk Febrile Neutropenia" , "primary_symptoms" : ["fever" , "neutrophils<0.5"] , "red_flag_symptoms" : ["hypotension" , "mucositis"] , "initial_questions" : ["Chemotherapy cycle?" , "Central line?" , "Antibiotics started?"] , "follow_up_questions" : ["MASCC score?" , "Source identified?" , "Antifungal indicated?"] , "emergency_criteria" : "Shock or MASCC<21" , "routine_criteria" : "Low-risk neutropenia" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "782736009"},

 # ---------------------- TOXICOLOGICAL/POISONING (10) ----------------------
 {"protocol_code" : "PARACETAMOL_OD" , "category" : "Toxicological/Poisoning" , "condition_name" : "Paracetamol Overdose" , "primary_symptoms" : ["nausea" , "vomiting"] , "red_flag_symptoms" : ["hepatotoxicity" , "metabolic_acidosis"] , "initial_questions" : ["Time of ingestion?" , "Amount taken?" , "Staggered overdose?"] , "follow_up_questions" : ["Alcohol co-ingestion?" , "NAC indicated?" , "INR rising?"] , "emergency_criteria" : "Above treatment line or hepatotoxicity" , "routine_criteria" : "Below treatment line, <8g total" , "self_care_criteria" : "Education on safe dosing" , "evidence_level" : "A" , "fhir_code" : "86977007"},
 {"protocol_code" : "SALICYLATE_OD" , "category" : "Toxicological/Poisoning" , "condition_name" : "Salicylate Poisoning" , "primary_symptoms" : ["tinnitus" , "confusion"] , "red_flag_symptoms" : ["altered_mental_status" , "pulmonary_edema"] , "initial_questions" : ["Aspirin amount?" , "Time since ingestion?" , "Chronic vs acute?"] , "follow_up_questions" : ["Salicylate level?" , "Blood gas done?" , "Dialysis indicated?"] , "emergency_criteria" : "Level>500 mg/L or severe symptoms" , "routine_criteria" : "Mild symptoms, level<300" , "self_care_criteria" : "Supportive care only" , "evidence_level" : "A" , "fhir_code" : "35656007"},
 {"protocol_code" : "TRICYCLIC_OD" , "category" : "Toxicological/Poisoning" , "condition_name" : "Tricyclic Antidepressant Overdose" , "primary_symptoms" : ["drowsiness" , "dry_mouth"] , "red_flag_symptoms" : ["QRS_widening" , "seizures"] , "initial_questions" : ["Which TCA?" , "Amount ingested?" , "Co-ingestion?"] , "follow_up_questions" : ["ECG changes?" , "Sodium bicarbonate given?" , "Activated charcoal?"] , "emergency_criteria" : "QRS>100ms or arrhythmias" , "routine_criteria" : "Mild sedation, normal ECG" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "292120005"},
 {"protocol_code" : "METHANOL_OD" , "category" : "Toxicological/Poisoning" , "condition_name" : "Methanol Poisoning" , "primary_symptoms" : ["visual_disturbance" , "nausea"] , "red_flag_symptoms" : ["blindness" , "severe_acidosis"] , "initial_questions" : ["Alcohol substitute?" , "Visual symptoms?" , "Amount consumed?"] , "follow_up_questions" : ["Methanol level?" , "Fomepizole available?" , "Dialysis needed?"] , "emergency_criteria" : "Visual symptoms or severe acidosis" , "routine_criteria" : "Asymptomatic with low level" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "35331000"},
 {"protocol_code" : "CARBON_MONOXIDE" , "category" : "Toxicological/Poisoning" , "condition_name" : "Carbon Monoxide Poisoning" , "primary_symptoms" : ["headache" , "dizziness"] , "red_flag_symptoms" : ["altered_consciousness" , "cherry_red_skin"] , "initial_questions" : ["Exposure source?" , "Household members affected?" , "Time of exposure?"] , "follow_up_questions" : ["COHb level?" , "Hyperbaric oxygen indicated?" , "Neurological deficit?"] , "emergency_criteria" : "COHb>25% or neurological symptoms" , "routine_criteria" : "Mild symptoms, COHb<15%" , "self_care_criteria" : "Source removal and ventilation" , "evidence_level" : "A" , "fhir_code" : "65606003"},
 {"protocol_code" : "ORGANOPHOSPHATE" , "category" : "Toxicological/Poisoning" , "condition_name" : "Organophosphate Poisoning" , "primary_symptoms" : ["muscle_fasciculation" , "excessive_salivation"] , "red_flag_symptoms" : ["respiratory_paralysis" , "seizures"] , "initial_questions" : ["Pesticide exposure?" , "Cholinergic symptoms?" , "Skin contamination?"] , "follow_up_questions" : ["Atropine given?" , "Pralidoxime available?" , "Decontamination done?"] , "emergency_criteria" : "Respiratory failure or severe cholinergic crisis" , "routine_criteria" : "Mild cholinergic symptoms" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "41165007"},
 {"protocol_code" : "DIGITALIS_TOXICITY" , "category" : "Toxicological/Poisoning" , "condition_name" : "Digitalis Toxicity" , "primary_symptoms" : ["nausea" , "visual_disturbance"] , "red_flag_symptoms" : ["arrhythmias" , "hyperkalemia"] , "initial_questions" : ["Digoxin dose?" , "Renal function?" , "Drug interactions?"] , "follow_up_questions" : ["Digoxin level?" , "Fab fragments indicated?" , "Electrolyte status?"] , "emergency_criteria" : "Hemodynamically significant arrhythmias" , "routine_criteria" : "Asymptomatic elevated level" , "self_care_criteria" : "Dose adjustment only" , "evidence_level" : "A" , "fhir_code" : "79855005"},
 {"protocol_code" : "BETA_BLOCKER_OD" , "category" : "Toxicological/Poisoning" , "condition_name" : "Beta-blocker Overdose" , "primary_symptoms" : ["bradycardia" , "hypotension"] , "red_flag_symptoms" : ["cardiogenic_shock" , "heart_block"] , "initial_questions" : ["Which beta-blocker?" , "Time of ingestion?" , "Cardiac symptoms?"] , "follow_up_questions" : ["Glucagon available?" , "Atropine tried?" , "High-dose insulin?"] , "emergency_criteria" : "Hemodynamic instability" , "routine_criteria" : "Mild bradycardia, stable BP" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "406165002"},
 {"protocol_code" : "IRON_OVERDOSE" , "category" : "Toxicological/Poisoning" , "condition_name" : "Iron Overdose" , "primary_symptoms" : ["nausea" , "abdominal_pain"] , "red_flag_symptoms" : ["GI_bleeding" , "shock"] , "initial_questions" : ["Iron preparation type?" , "Amount ingested?" , "Vomiting blood?"] , "follow_up_questions" : ["Serum iron level?" , "Desferrioxamine needed?" , "Metabolic acidosis?"] , "emergency_criteria" : "Iron>500 mcg/dL or systemic toxicity" , "routine_criteria" : "Mild GI symptoms only" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "235726005"},
 {"protocol_code" : "CYANIDE_POISONING" , "category" : "Toxicological/Poisoning" , "condition_name" : "Cyanide Poisoning" , "primary_symptoms" : ["altered_mental_status" , "dyspnea"] , "red_flag_symptoms" : ["cardiac_arrest" , "lactic_acidosis"] , "initial_questions" : ["Exposure source?" , "Smoke inhalation?" , "Rapid onset?"] , "follow_up_questions" : ["Cyanide antidote kit?" , "Hydroxocobalamin available?" , "Lactate level?"] , "emergency_criteria" : "High clinical suspicion with collapse" , "routine_criteria" : "Possible exposure, asymptomatic" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "35331000"},

 # ---------------------- GYNECOLOGICAL (10) ----------------------
 {"protocol_code" : "OVARIAN_TORSION" , "category" : "Gynecological" , "condition_name" : "Ovarian Torsion" , "primary_symptoms" : ["sudden_pelvic_pain" , "nausea"] , "red_flag_symptoms" : ["vomiting" , "absent_ovarian_flow"] , "initial_questions" : ["Onset of pain?" , "Previous ovarian cysts?" , "Pain severity?"] , "follow_up_questions" : ["Doppler ultrasound done?" , "Whirlpool sign present?" , "Pregnancy status?"] , "emergency_criteria" : "Clinical suspicion with absent flow on Doppler" , "routine_criteria" : "Ovarian cyst without torsion" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "59156009"},
 {"protocol_code" : "PID_SEVERE" , "category" : "Gynecological" , "condition_name" : "Severe Pelvic Inflammatory Disease" , "primary_symptoms" : ["pelvic_pain" , "fever"] , "red_flag_symptoms" : ["tubo_ovarian_abscess" , "sepsis"] , "initial_questions" : ["Sexual history?" , "Vaginal discharge?" , "IUD present?"] , "follow_up_questions" : ["Cervical motion tenderness?" , "Antibiotic allergies?" , "HIV status?"] , "emergency_criteria" : "TOA or sepsis with PID" , "routine_criteria" : "Mild PID, outpatient treatment" , "self_care_criteria" : "STI prevention counseling" , "evidence_level" : "A" , "fhir_code" : "198130006"},
 {"protocol_code" : "PLACENTAL_ABRUPTION" , "category" : "Gynecological" , "condition_name" : "Placental Abruption" , "primary_symptoms" : ["abdominal_pain" , "vaginal_bleeding"] , "red_flag_symptoms" : ["fetal_distress" , "DIC"] , "initial_questions" : ["Gestational age?" , "Trauma history?" , "Hypertension?"] , "follow_up_questions" : ["Fetal heart rate?" , "Coagulation studies?" , "Blood type/crossmatch?"] , "emergency_criteria" : "Severe abruption with fetal compromise" , "routine_criteria" : "Marginal abruption, stable" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "415105001"},
 {"protocol_code" : "AMNIOTIC_EMBOLISM" , "category" : "Gynecological" , "condition_name" : "Amniotic Fluid Embolism" , "primary_symptoms" : ["sudden_dyspnea" , "hypotension"] , "red_flag_symptoms" : ["cardiovascular_collapse" , "DIC"] , "initial_questions" : ["Labor stage?" , "Previous AFE?" , "Sudden collapse?"] , "follow_up_questions" : ["Coagulopathy present?" , "Seizures?" , "Fetal status?"] , "emergency_criteria" : "Sudden cardiorespiratory collapse in labor" , "routine_criteria" : "None - always emergency" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "88144003"},
 {"protocol_code" : "POSTPARTUM_HEMORRHAGE" , "category" : "Gynecological" , "condition_name" : "Primary Postpartum Hemorrhage" , "primary_symptoms" : ["excessive_bleeding" , ">500ml_blood_loss"] , "red_flag_symptoms" : ["hypovolemic_shock" , "uterine_atony"] , "initial_questions" : ["Blood loss estimate?" , "Retained placenta?" , "Previous PPH?"] , "follow_up_questions" : ["Uterotonic drugs given?" , "Exploration done?" , "Coagulopathy?"] , "emergency_criteria" : ">1000ml blood loss or shock" , "routine_criteria" : "Minor bleeding <500ml" , "self_care_criteria" : "Active management third stage" , "evidence_level" : "A" , "fhir_code" : "200363002"},
 {"protocol_code" : "PREECLAMPSIA_SEVERE" , "category" : "Gynecological" , "condition_name" : "Severe Preeclampsia/Eclampsia" , "primary_symptoms" : ["severe_headache" , "visual_disturbance"] , "red_flag_symptoms" : ["BP>160/110" , "seizures"] , "initial_questions" : ["Gestational age?" , "Previous preeclampsia?" , "Proteinuria?"] , "follow_up_questions" : ["Magnesium sulfate given?" , "Liver enzymes?" , "Platelet count?"] , "emergency_criteria" : "Eclampsia or severe features" , "routine_criteria" : "Mild preeclampsia" , "self_care_criteria" : "Blood pressure monitoring" , "evidence_level" : "A" , "fhir_code" : "198992004"},
 {"protocol_code" : "UTERINE_RUPTURE" , "category" : "Gynecological" , "condition_name" : "Uterine Rupture" , "primary_symptoms" : ["severe_abdominal_pain" , "loss_of_contractions"] , "red_flag_symptoms" : ["fetal_bradycardia" , "maternal_shock"] , "initial_questions" : ["Previous cesarean?" , "Trial of labor?" , "Sudden pain?"] , "follow_up_questions" : ["Fetal heart rate?" , "Palpable fetal parts?" , "Blood loss?"] , "emergency_criteria" : "Complete rupture with fetal compromise" , "routine_criteria" : "Dehiscence without rupture" , "self_care_criteria" : "None" , "evidence_level" : "A" , "fhir_code" : "71271003"},
 {"protocol_code" : "OVARIAN_HYPERSTIM" , "category" : "Gynecological" , "condition_name" : "Ovarian Hyperstimulation Syndrome" , "primary_symptoms" : ["abdominal_distension" , "weight_gain"] , "red_flag_symptoms" : ["severe_ascites" , "thromboembolism"] , "initial_questions" : ["IVF cycle?" , "hCG trigger?" , "Fluid intake?"] , "follow_up_questions" : ["Electrolyte balance?" , "Renal function?" , "Thromboprophylaxis?"] , "emergency_criteria" : "Severe OHSS with complications" , "routine_criteria" : "Mild OHSS, outpatient management" , "self_care_criteria" : "Adequate hydration" , "evidence_level" : "B" , "fhir_code" : "237121007"},
 {"protocol_code" : "VULVAR_HEMATOMA" , "category" : "Gynecological" , "condition_name" : "Vulvar Hematoma" , "primary_symptoms" : ["vulvar_pain" , "swelling"] , "red_flag_symptoms" : ["expanding_hematoma" , "hemodynamic_instability"] , "initial_questions" : ["Recent delivery?" , "Trauma?" , "Anticoagulant use?"] , "follow_up_questions" : ["Size of hematoma?" , "Urinary retention?" , "Active bleeding?"] , "emergency_criteria" : "Large expanding hematoma >5cm" , "routine_criteria" : "Small stable hematoma <3cm" , "self_care_criteria" : "Ice packs, analgesia" , "evidence_level" : "B" , "fhir_code" : "271901008"},

 # ---------------------- PSYCHOLOGICAL (10) ----------------------
 {"protocol_code" : "ACUTE_PSYCHOSIS" , "category" : "Psychological" , "condition_name" : "Acute Psychosis" , "primary_symptoms" : ["delusions" , "hallucinations"] , "red_flag_symptoms" : ["agitation" , "violence_risk"] , "initial_questions" : ["First episode?" , "Substance use?" , "Medication compliance?"] , "follow_up_questions" : ["Insight present?" , "Family history?" , "Medical causes excluded?"] , "emergency_criteria" : "Acute agitation or violence risk" , "routine_criteria" : "Stable psychosis, insight present" , "self_care_criteria" : "Medication adherence support" , "evidence_level" : "A" , "fhir_code" : "69322001"},
 {"protocol_code" : "SUICIDE_ATTEMPT" , "category" : "Psychological" , "condition_name" : "Suicide Attempt/Ideation" , "primary_symptoms" : ["suicidal_thoughts" , "self_harm"] , "red_flag_symptoms" : ["active_plan" , "means_available"] , "initial_questions" : ["Intent to die?" , "Method planned?" , "Previous attempts?"] , "follow_up_questions" : ["Protective factors?" , "Alcohol/drugs?" , "Support network?"] , "emergency_criteria" : "High suicide risk with plan/means" , "routine_criteria" : "Low risk, good support" , "self_care_criteria" : "Crisis contact numbers" , "evidence_level" : "A" , "fhir_code" : "44814006"},
 {"protocol_code" : "SEVERE_DEPRESSION" , "category" : "Psychological" , "condition_name" : "Severe Depression with Psychosis" , "primary_symptoms" : ["low_mood" , "anhedonia"] , "red_flag_symptoms" : ["psychotic_features" , "catatonia"] , "initial_questions" : ["Duration of symptoms?" , "Previous episodes?" , "Medication history?"] , "follow_up_questions" : ["Appetite/sleep?" , "Guilt/worthlessness?" , "ECT indicated?"] , "emergency_criteria" : "Catatonia or severe psychotic depression" , "routine_criteria" : "Moderate depression, functioning" , "self_care_criteria" : "Lifestyle interventions" , "evidence_level" : "A" , "fhir_code" : "36923009"},
 {"protocol_code" : "MANIC_EPISODE" , "category" : "Psychological" , "condition_name" : "Acute Manic Episode" , "primary_symptoms" : ["elevated_mood" , "hyperactivity"] , "red_flag_symptoms" : ["grandiosity" , "poor_judgment"] , "initial_questions" : ["Sleep pattern?" , "Spending sprees?" , "Risk-taking behavior?"] , "follow_up_questions" : ["Lithium level?" , "Antipsychotic needed?" , "Insight present?"] , "emergency_criteria" : "Severe mania with risk behaviors" , "routine_criteria" : "Hypomania, stable" , "self_care_criteria" : "Sleep hygiene, mood monitoring" , "evidence_level" : "A" , "fhir_code" : "61403008"},
 {"protocol_code" : "ACUTE_ANXIETY" , "category" : "Psychological" , "condition_name" : "Severe Anxiety/Panic Disorder" , "primary_symptoms" : ["panic_attacks" , "chest_pain"] , "red_flag_symptoms" : ["agoraphobia" , "functional_impairment"] , "initial_questions" : ["Trigger identified?" , "Physical symptoms?" , "Caffeine intake?"] , "follow_up_questions" : ["Avoidance behaviors?" , "Previous therapy?" , "Medication response?"] , "emergency_criteria" : "Severe panic with medical mimicry" , "routine_criteria" : "Mild anxiety, coping well" , "self_care_criteria" : "Relaxation techniques" , "evidence_level" : "A" , "fhir_code" : "197480006"},
 {"protocol_code" : "DELIRIUM_ACUTE" , "category" : "Psychological" , "condition_name" : "Acute Delirium" , "primary_symptoms" : ["confusion" , "altered_consciousness"] , "red_flag_symptoms" : ["fluctuating_course" , "visual_hallucinations"] , "initial_questions" : ["Onset timeline?" , "Medication changes?" , "Infection present?"] , "follow_up_questions" : ["Cognitive baseline?" , "Metabolic causes?" , "Sleep-wake cycle?"] , "emergency_criteria" : "Hyperactive delirium with agitation" , "routine_criteria" : "Hypoactive delirium, stable" , "self_care_criteria" : "Environmental modification" , "evidence_level" : "A" , "fhir_code" : "419284004"},
 {"protocol_code" : "CATATONIA" , "category" : "Psychological" , "condition_name" : "Catatonic Syndrome" , "primary_symptoms" : ["stupor" , "posturing"] , "red_flag_symptoms" : ["waxy_flexibility" , "mutism"] , "initial_questions" : ["Duration of symptoms?" , "Associated fever?" , "Previous episodes?"] , "follow_up_questions" : ["Bush-Francis scale?" , "Lorazepam response?" , "Medical workup done?"] , "emergency_criteria" : "Malignant catatonia with fever" , "routine_criteria" : "Mild catatonic features" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "69369003"},
 {"protocol_code" : "ALCOHOL_WITHDRAWAL" , "category" : "Psychological" , "condition_name" : "Severe Alcohol Withdrawal" , "primary_symptoms" : ["tremor" , "sweating"] , "red_flag_symptoms" : ["delirium_tremens" , "seizures"] , "initial_questions" : ["Last drink?" , "Daily intake?" , "Previous withdrawal?"] , "follow_up_questions" : ["CIWA score?" , "Thiamine given?" , "Seizure history?"] , "emergency_criteria" : "Delirium tremens or seizures" , "routine_criteria" : "Mild withdrawal, stable" , "self_care_criteria" : "Gradual reduction plan" , "evidence_level" : "A" , "fhir_code" : "13746004"},
 {"protocol_code" : "NEUROLEPTIC_MS" , "category" : "Psychological" , "condition_name" : "Neuroleptic Malignant Syndrome" , "primary_symptoms" : ["hyperthermia" , "muscle_rigidity"] , "red_flag_symptoms" : ["altered_mental_status" , "autonomic_instability"] , "initial_questions" : ["Antipsychotic use?" , "Fever onset?" , "Muscle stiffness?"] , "follow_up_questions" : ["CK level?" , "Dopamine agonist available?" , "ICU needed?"] , "emergency_criteria" : "Classic tetrad with antipsychotic exposure" , "routine_criteria" : "Drug-induced parkinsonism" , "self_care_criteria" : "None" , "evidence_level" : "B" , "fhir_code" : "162317007"},
 {"protocol_code" : "SEROTONIN_SYNDROME" , "category" : "Psychological" , "condition_name" : "Serotonin Syndrome" , "primary_symptoms" : ["altered_mental_status" , "hyperthermia"] , "red_flag_symptoms" : ["clonus" , "hyperreflexia"] , "initial_questions" : ["Serotonergic drugs?" , "Recent changes?" , "Onset timeline?"] , "follow_up_questions" : ["Hunter criteria met?" , "Cyproheptadine available?" , "Drug interactions?"] , "emergency_criteria" : "Severe hyperthermia >41°C or rigidity" , "routine_criteria" : "Mild serotonergic effects" , "self_care_criteria" : "Drug interaction awareness" , "evidence_level" : "B" , "fhir_code" : "55761008"},
 {"protocol_code": "CG192_POSTPARTUM_DEPRESSION", "category": "Psychological", "condition_name": "Postpartum Depression", "primary_symptoms": ["low_mood", "sadness", "anxiety", "fatigue", "bonding_difficulties"], "red_flag_symptoms": ["suicidal_ideation", "infanticide_thoughts", "severe_anxiety", "psychotic_features"], "initial_questions": ["When did your baby arrive?", "How long have you felt this way?", "Are you having thoughts of harming yourself or your baby?"], "follow_up_questions": ["Are you able to bond with your baby?", "Do you have family support?", "Are you breastfeeding?", "Any sleep when baby sleeps?"], "emergency_criteria": "Thoughts of self-harm or harm to baby, severe bonding failure, psychotic symptoms", "routine_criteria": "Mild-moderate symptoms, good support network, no suicidal ideation", "self_care_criteria": "Peer support groups, sleep hygiene, gradual activity increase", "evidence_level": "A", "fhir_code": "58703003"}

]
